### ISSUE TITLE
The option cannot be selected correctly while the ng-model is not a object

### ISSUE THREAD

**Issue by edisonh** [leocaseiro/angular-chosen#100]
````html
<select chosen ng-model="item">
    <option value="option1">option1</option>
    <option value="option1">option2</option>
</select>
````

````javascript
$scope.item = "option1";
````

And I fixed by setting the config 'terminal' to 'false' (or deleting it) in the directive code.

````javascript
terminal: true // delete line 36
````

**Comment by leocaseiro** [comment]
As you can se in the docs, Angular Chosen works better with `ngOptions` and `ngModel`, avoid using `ng-repeat`.

PS: We removed terminal on PR #157
