### ISSUE TITLE
Chosen problem with jQuery dependencies.

### ISSUE THREAD

**Issue by victorgb6** [leocaseiro/angular-chosen#103]
Hi, I've just go mad for a few days trying to make chosen for angular work, and finally I discovered that the problem was the order i was getting the scripts.

I was calling jQuery at the end of the HTML below the end body tag, but this seems to be a problem with the angular-chosen. The solution is to call the jQuery script below the angular script.

I think you should write that on the readme or documentation, someone could find that helpful in the future.

**Comment by PhiLhoSoft** [comment]
Actually, I think jQuery script tag should be before the Angular one, so that Angular uses jQuery instead of the simpler [jqLite](http://www.bennadel.com/blog/2752-using-jquery-instead-of-jqlite-in-angularjs.htm). In other words, this will also be beneficial to your other Angular code.

**Comment by leocaseiro** [comment]
Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

I've updated master with the PR #88. Could you please check if works for you? Thanks

**Comment by leocaseiro** [comment]
Hi @victorgb6 and @PhiLhoSoft, actually that's a normal behavior from AngularJS.
By default, AngularJS comes with jqLite, with that said, if you want to use jQuery you must to insert jQuery on top of your application.

That information is at [AngularJS Docs](https://docs.angularjs.org/api/ng/function/angular.element)
> To use jQuery, simply ensure it is loaded before the angular.js file. You can also use the ngJq directive to specify that jqlite should be used over jQuery, or to use a specific version of jQuery if multiple versions exist on the page.
