### ISSUE TITLE
Multiple-Select Chosen with remote source and query-parameter

### ISSUE THREAD

**Issue by paroos** [leocaseiro/angular-chosen#104]
Hi there

Is there a chance to use multiple-select chosen with a remote source and a query-parameter as filter?

My HTTP-REST interface looks like /resource/q=myfilterterm

Your example in my context:

    angular.module('App', ['ngResource', 'localytics.directives'])
    .controller('BeerCtrl', function($http, $scope) {
     $scope.beers = $http.get('/resource, {
             params: {
                                 'q': <how can I set / bind this?>
                           }
             })
    });

I don't know how I can set/bind the query parameter by the user's input string in chosen. 

Can you help me?

Thank you!

Kind regards, patrick

**Comment by leocaseiro** [comment]
Please see https://github.com/leocaseiro/angular-chosen/issues/148#issuecomment-194287548
