### ISSUE TITLE
Is there an onOpen or onShow event?

### ISSUE THREAD

**Issue by geoidesic** [leocaseiro/angular-chosen#105]
It would be handy to be able to subscribe to an onShow or onOpen event. For example.. the chosen is in a panel with a fixed height and overflow:hidden. Would be useful to be able to change the panel's overflow attribute when the chosen element opens.

**Comment by lpsBetty** [comment]
there are events, you can use it like this: (I use it in a directive ;))

````
element.on('chosen:showing_dropdown', function (e, obj) { 
});
````

More info: https://harvesthq.github.io/chosen/options.html#triggered-events

**Comment by leocaseiro** [comment]
I think the @lpsBetty answer your question. That would be nice having your confirmation @geoidesic.

For the time being, I'm closing this Issue.

Thanks
