### ISSUE TITLE
Can the jQuery dependency be removed

### ISSUE THREAD

**Issue by solenoo** [leocaseiro/angular-chosen#108]
So yeah as the tittle says, can it please be removed.

**Comment by PhiLhoSoft** [comment]
Given that [Chosen](http://harvesthq.github.io/chosen/) is a jQuery plug-in, it seems unlikely to be possible to remove the latter...

**Comment by rshackleton-netc** [comment]
There is a prototype version available: http://harvesthq.github.io/chosen/index.proto.html

**Comment by leocaseiro** [comment]
Sorry, It's not possible as Chosen is a jQuery plugin.
