### ISSUE TITLE
Value is not updated when ng-options is an object.

### ISSUE THREAD

**Issue by bertugolu** [leocaseiro/angular-chosen#109]
Sorry if the title is misleading, but I am trying my best to describe the issue.

I have this data source:

	$scope.optionsFromQuery = [
			{"ID": 1, "Value": "Cheese One"},
			{"ID": 2, "Value": "Cheese Two"},
			{"ID": 3, "Value": "Cheese Three"},
			{"ID": 4, "Value": "Cheese Four"},
			{"ID": 5, "Value": "Cheese Five"},
		];

HTML looks as follows:

<select
    chosen
    data-placeholder="Choose Your Own Adventure"
    no-results-text="'Tough luck'"
    ng-model="foo"
    ng-options="value.Value for value in optionsFromQuery"
    style="width:200px;">
    <option value=""></option>
  </select>

If the value of a "Value" is changed, this is not reflected in the dropdown. Eg: button that ng-click does: 	$scope.optionsFromQuery[0].Value = "bacon";

To re-create, i simply downloaded the example and plugged those values.

The issue is happening since there is a watchcollection, such changes are not triggering the watch, thus never updating.

**Comment by jhernandezgt** [comment]
You should try this on your ng-options 
     
     ng-options="value.ID as value.Value for value in optionsFromQuery"

https://docs.angularjs.org/api/ng/directive/ngOptions

**Comment by leocaseiro** [comment]
Hi @bertugolu, I believe @jorgeahernandez 's answer works pretty well.
