### ISSUE TITLE
v1.0.6: If select first entry, then I cannot select last

### ISSUE THREAD

**Issue by mobiusinversion** [leocaseiro/angular-chosen#110]
If I load the page, select the first entry in the select, and then I try to select the last, I am not able to with an error:

Uncaught TypeError: Cannot set property 'selected' of undefined

**Comment by mattlanham** [comment]
I also have this issue.

**Comment by sayat91** [comment]
Add empty <option> tag to select

**Comment by mattlanham** [comment]
Yea the issue with that is that it then shows up as a choice, which isn't really what I want.

**Comment by plantric** [comment]
Just comment out origRender() line in the following section
            ngModel.$render = function() {
              //origRender();
              updateSelectElement(element, this);
              return initOrUpdate();

Also I made the changes to enable two way data binding but need more testing.

**Comment by joerideg** [comment]
That fix doesnt work for me @plantric. Selecting the last entry on the first selection works but as a second selection it is the same error.

**Comment by joerideg** [comment]
Always wise to read the documentation first.
https://github.com/localytics/angular-chosen#integration-with-ngmodel-and-ngoptions

**Comment by leocaseiro** [comment]
Thank you @joerideg 

> Note: the empty ```<option>``` element is mandatory when using ```allow-single-deselect```
