### ISSUE TITLE
Create new option if a value is entered that is not in the list

### ISSUE THREAD

**Issue by geoidesic** [leocaseiro/angular-chosen#112]
How can this be achieved?

The idea is that if you type in a value that's not in the list and submit, it will be added as a new option in the list.

**Comment by colinjlacy** [comment]
:+1:

**Comment by leocaseiro** [comment]
Sounds interesting, I like that!

I'll make sure that we get the typed text (Ref #148). Probably I'll get a callback function, so the action of create new item won't be at the core. It can be async or not, depending on your application...

**Comment by leocaseiro** [comment]
Hi @geoidesic and @colinjlacy,

I've added **v.1.3.0** compatibility with the Forked Chosen from @koenpunt, so we're able to add/create new item.

First step is switch from chosen.js and chosen.css to koenpunt/chosen versions.
You can download it here: https://github.com/koenpunt/chosen/releases

Then, you'll have 4 new attributes: `create-option-text`, `persistent-create-option`, `skip-no-results` and `create-option`

To Create new option, use like that:

```javascript
$scope.name = 'Multiple Angular Chosen Example add new option';
  $scope.state = ['California', 'Arizona'];
  $scope.states = [
    'Alaska',
    'Arizona',
    'Arkansas',
    'California'
  ];
  
  $scope.createOption = function(term) {
    $scope.$apply(function() {
      $scope.states.push(term);
      $scope.state.push(term);
    });
  }
```

```html
<select multiple
        chosen
        create-option-text="'Create item'"
        persistent-create-option="true"
        skip-no-results="true"
        create-option="createOption"
        ng-model="state"
        ng-options="s for s in states">
  <option value=""></option>
</select>
```

Here is an example working http://plnkr.co/edit/xZ5XbO?p=preview

**Comment by GustavoCostaW** [comment]
@leocaseiro ( Parabéns pelo modulo :) ) congratz for amazing module! For performance, try change $apply for simple $digest in your example, ($apply run $digest in all $scope in your project when createOptions is called)

  $scope.createOption = function(term) {
 
      $scope.states.push(term);
      $scope.state.push(term);
      
      //$digest run only this $scope and in all their children (chosen directive is here and run $digest)


      $scope.$digest();
  }

**Comment by leocaseiro** [comment]
Done. Cheers @GustavoCostaW!

**Comment by GustavoCostaW** [comment]
@leocaseiro what is the best way to "watch" when your chosen directive, "add", "remove" or create new option, and get the current event? I tried using $watch, but I do know what is removed or added or  created, you understand me?

**Comment by leocaseiro** [comment]
Hi @GustavoCostaW,

I'm sorry for me late reply.

Unfortunately, you'll have to watch your full list. That's how I normally do.

Because you have an array, you can use the $watchCollection:

```javascript
 $scope.$watchCollection('state', function(newList, oldList) {
    console.log('before add list', oldList);
    console.log('after add new item to list', newList);
  });
```

Example http://plnkr.co/edit/YZJD8O?p=preview


If you are interested in watch in deep your collection, you should use the 3rd parameter(objectEquality) as `true`:

```javascript
 $scope.$watch('state', function(newList, oldList) {
    console.log('before add list', oldList);
    console.log('after add new item to list', newList);
  }, true); // note the true here for objectEquality
```

Read more: https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch

**Comment by GustavoCostaW** [comment]
@leocaseiro all right, I thought about using $watchCollection too.
