### ISSUE TITLE
Arabic Language Support

### ISSUE THREAD

**Issue by nidhinkktl** [leocaseiro/angular-chosen#114]
What about the Arabic Language Support?

**Comment by Ahmed-Saleh** [comment]
+1

**Comment by leocaseiro** [comment]
Does Chosen works with Arabic? It shouldn't be an issue.

PR are very welcome for that fix.

**Comment by leocaseiro** [comment]
Can you try translate like the issue #121 ?

**Comment by leocaseiro** [comment]
Hi @nidhinkktl and @Ahmed-Saleh, I'm not sure what should be for supporting Arabic Language. Set right to left. What else would need?

I have a plunkr which seems working just fine: http://plnkr.co/edit/F3pLqA?p=preview

First, set the `class="chosen-rtl"`, then set your [language options](http://leocaseiro.github.io/angular-chosen/#translate):

```html
<select class="chosen-rtl" chosen dir="rtl" multiple 
     no-results-text="'لا توجد نتائج مطابقة'"
     placeholder-text-multiple="'تحديد بعض الخيارات'"
     ng-model="state" ng-options="opt for opt in options">
    <option value=""></option>
  </select>
````

```javascript
$scope.opt = [];
  $scope.options = [
    'بل ليرتفعة',
    'الثان',
    'ية لك',
    'ل. ثم'
  ];
```

I'm closing this issue, but few free to report my support it should be done!

**Comment by Ahmed-Saleh** [comment]
looks all good, thanks +1
