### ISSUE TITLE
ng-change event doesn't get triggered when using the single deselect ??? how can i do it???

### ISSUE THREAD

**Issue by ImranMulani** [leocaseiro/angular-chosen#119]
ng-change event doesn't get triggered when using the single deselect ??? how can i do it???

**Comment by leocaseiro** [comment]
Can you use $scope.$watch?

Like so: 

```javasctipt
$scope.state = ['California', 'Arizona'];
  $scope.states = [
    'Alaska',
    'Arizona',
    'Arkansas',
    'California'
  ];
  
  $scope.$watch('state', function(changed) {
    console.log('state changed to ', changed);
  });

```

Example on Plunkr: http://plnkr.co/edit/DuFbSh?p=preview

**Comment by leocaseiro** [comment]
I believe `ng-changed` has been fixed in a later version.

Check my example http://plnkr.co/edit/Zejg6f?p=preview

Even though, you could always use `$scope.$watch` with `ngModel`.
