### ISSUE TITLE
Disabling autocomplete

### ISSUE THREAD

**Issue by iamryandrake** [leocaseiro/angular-chosen#120]
In Chrome, on any Chosen object, I see a list of addresses that appear when I click on the Chosen input field, even though the element isn't an address type.

Any idea how to disable the browser autocomplete in these cases?

I've already tried autocomplete="off" and autocomplete="false"...

**Comment by leocaseiro** [comment]
Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

What you're looking for is the attribute `allow-single-deselect`

[Example in docs](http://leocaseiro.github.io/angular-chosen/#chosen-attributes)
