### ISSUE TITLE
How to use angular-translate

### ISSUE THREAD

**Issue by gaui** [leocaseiro/angular-chosen#121]
How can I use angular-translate in conjunction with this library?

Single:

	<select class="chosen-select"
			chosen
			allow-single-deselect="true"
			data-placeholder="WE NEED TRANSLATION"
			no-results-text="WE NEED TRANSLATION"
			ng-model="someModel"
			ng-options="value for value in array">
	</select>

Multiple:

	<select class="chosen-select"
			chosen
			multiple
			allow-single-deselect="true"
			placeholder-text-multiple="WE NEED TRANSLATION"
			no-results-text="WE NEED TRANSLATION"
			data-ng-model="someModel"
			data-ng-options="value for value in array">
	</select>

**Comment by babbelnedd** [comment]
+1

**Comment by boeserwolf** [comment]
+1

**Comment by cwtsui** [comment]
+1
For single, I have tried following method
```
<select class="chosen-select"
        chosen
        allow-single-deselect="true"
        data-placeholder="WE NEED TRANSLATION"
        no-results-text="WE NEED TRANSLATION"
        ng-model="someModel"
        ng-options="value | translate for value in array">
</select>
```

but item does not translate after change language using *$translate.use()*

**Comment by vstene** [comment]
It's possible to translate it using the translate filter.
```
<select chosen
        data-placeholder="{{ 'my.translation.placeholder' | translate }}"
        no-results-text="{{ 'my.translation.noResults' | translate }}" >
</select>
```

However, attributes are not watched so if the translations are changed/loaded after the directive has been initialized you are stuck with the first or no translation. Which sucks.

**Comment by vstene** [comment]
It's possible to translate it using the translate filter. Make sure you remember to wrap it around with `'` so it's a string.
```
<select chosen
        placeholder-single-text="'{{ 'my.translation.placeholder' | translate }}'"
        no-results-text="'{{ 'my.translation.noResults' | translate }}'" >
</select>
```

You cannot use `data-placeholder` as this attribute is not watched. Use one of these whitelisted attributes:
https://github.com/localytics/angular-chosen/blob/master/src/chosen.coffee#L9-L23

**Comment by lpsBetty** [comment]
I always use  ``data-placeholder="{{ 'translation_key' | translate }}"`` and it works?

**Comment by leocaseiro** [comment]
They are expression attributes, so you need to use a variable or quote, like so:

* ```no-results-text="'No results match'"```
* ```placeholder-text-multiple="'Select Some Options''"```
* ```placeholder-text-single="'Select an Option''"```

Here's an example in Brazilian Portuguese: http://plnkr.co/edit/P3bWW2?p=preview

**Comment by stenmuchow** [comment]
@IpsBetty your method works - but there is a bug then when the dropdown is repopulated after page load the interpolation doesnt fire anymore.

**Comment by lpsBetty** [comment]
@stenmuchow there was an angular-chosen change that caused that this doesn't work anymore..

I now use this:

`placeholder-text-single="'{{::'translation_key' | translate}}'"`

**Comment by stenmuchow** [comment]
Aha - thanks for that - I missed the single quotes immediately inside the doubles. So many quotes....

**Comment by lpsBetty** [comment]
Yeah I also think that is a strange syntax ;)
