### ISSUE TITLE
Chosen eternally disable

### ISSUE THREAD

**Issue by marcoblos** [leocaseiro/angular-chosen#122]
When I use Chosen with a filter on array, like this:
```javascript
ng-options="tp for tp in array | filter:{type: 'NOT_DEFINED'}"
```
And when I select a option of chosen and click on button that change the variable **type** to another value, and repeat the process until finished my options on chosen, it disable, so far it's OK.
But, when I click in other button that change the variable **type** to 'NOT_DEFINED', the chosen don't return to enable.
The problem is solve with this code:

```javascript
if (attr.ngOptions && ngModel) {
    match = attr.ngOptions.match(NG_OPTIONS_REGEXP);
    valuesExpr = match[7];
    return scope.$watchCollection(valuesExpr, function(newVal, oldVal) {
        if (angular.isUndefined(newVal)) {
            return startLoading();
        } else {
            if (empty) {
                removeEmptyMessage();
            }
            stopLoading();
            if (isEmpty(newVal)) {
                return disableWithMessage();
             } else {
                 element.attr('data-placeholder', '').attr('disabled', false).trigger('chosen:updated');
             }
         }
     });
}
```
My code change  it is:
```javascript
} else {
     element.attr('data-placeholder', '').attr('disabled', false).trigger('chosen:updated');
}
```

Sorry for my english, I'm learning. :sweat_smile:

**Comment by leocaseiro** [comment]
Hi, first I'm really sorry for the delay. This project has a new maintainer (Read more #162)

I'm not sure what is exactly your scenario, could you please give me an example working on a plunkr/codepen?

Get from here, for example: http://plnkr.co/edit/1U8KCH?p=preview

What is this filter about? What is the type variable?

PS: You can write Portuguese if you'd like to. I'm Brazilian too :smile:
