### ISSUE TITLE
Chosen multiple select dropdown in IE causing huge blank space below the page ( only in IE)

### ISSUE THREAD

**Issue by bharos** [leocaseiro/angular-chosen#129]
I am using chosen for multiple select , with dropdown values from angular controller. Everything is fine in Mozilla and chrome.. But in IE (I am on IE 10,but I think this is present in IE 11 as well), the functionality is working, but after selecting an option from dropdown, the browser scrollbar becomes so small and large blank space is produced at bottom of page.. This is kind of weird, it sometimes becomes normal after a click outside or when page is scrolled.. But I guess this is a bug with chosen+ IE...
Please try this on a page with a browser scroll-bar ( ie. page which has content more than default browser window size), which has chosen multi-select dropdown...
Please tell if this is a known issue or any workarounds for this..

**Comment by bharos** [comment]
Also noted that this happens when chosen multiple select dropdown list has enough elements that the dropdown also has a scroll-bar..So IE is somewhat confused with browser and chosen scroll-bars I guess, but still am not able to get any idea on why it happens like this.

**Comment by slop3n** [comment]
Im also having this issue and the scenario is this:
I have 4 multiselects, the first 3 have defined lists of elements, the 4th is filtered by a combination of the first 3 using an ajax call. When there is no selected option from the first 3 multiselects the 4th one is cleared. Whenever i select something from the first 3 multiselects and quickly scroll down(only have to scroll down on my first attempt) i get a huge blank spot below my content(after the first attempt i get the huge blank spot every time i change an option from the multiselect). When i click on the 4th multiselect somehow the blank content is cleared. 
I also dont have any idea what/why this is happening. Just thought my scenario might help you

**Comment by leocaseiro** [comment]
Give a try on Internet Explorer 11 first as Microsoft dropped support to IE10.
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

Also, that would be nice having a [plunkr](https://plnkr.co/) or something similar so we could test.

**Comment by TimeToFixStuff** [comment]
Quick fix I'm using (chosen.jquery.js):


Chosen.prototype.results_build = function() {
...
      $(".chosen-results").css("overflow", "hidden");

      this.update_results_content(this.results_option_build({
        first: true
      }));

      $(".chosen-results").css("overflow", "scrollbar");
...
    };
