### ISSUE TITLE
Initial disabled select with ngDisabled

### ISSUE THREAD

**Issue by dfsq** [leocaseiro/angular-chosen#131]
Looks like the directive will remove previously set disabled attribute in `stopLoading` (this [line][1]) function:

```javascript
stopLoading = -> element.removeClass('loading').attr('disabled', false).trigger('chosen:updated')
```

Instead of always setting `false` directive should set current actual disabled property value:

```javascript
.attr('disabled', attr.disabled).
```

[1]: https://github.com/localytics/angular-chosen/blob/master/src/chosen.coffee#L49

**Comment by TwistyPop** [comment]
Actually what you probably want is something like this :

**Comment by TwistyPop** [comment]
You probably want to do this instead:

**Comment by jacobuk** [comment]
will this be picked soon?

**Comment by faelcorreia** [comment]
+1 for this solution. I hope to see this in the next release.

I was doing a plunker to open this exact issue. So here is the before and after the change:

http://plnkr.co/edit/YllQsUJNffuos8AxT7kf?p=preview
http://plnkr.co/edit/VaN1cAXAN1HYaxPxRUqZ?p=preview

**Comment by iksose** [comment]
Thanks

**Comment by DeanMW** [comment]
The above does not work for me as I have my chosen elements in a fieldset and the fieldset is what is disabling all of the children chosen elements. Does anyone have a fix for this? I can't seem to find an effective way to do this.

**Comment by leocaseiro** [comment]
Is the #117 really fix your issue?
