### ISSUE TITLE
angular-chosen won't disable with dynamic list of options (ng-options)

### ISSUE THREAD

**Issue by TwistyPop** [leocaseiro/angular-chosen#134]
When using ng-options in the chosen directive it appears that the disable functionality doesn't work.

Please see this plnkr: http://plnkr.co/It5mNWOfyPI8BWNV72Kd

The plunk contains a chosen select list with static options, which does disable and a list with dynamic options using ng-options which does not.

I believe the problem lies in the stopLoading function of the directive. It always sets the disable property to false when calling it. overriding the ng-disable value.

Thanks,

**Comment by leocaseiro** [comment]
Hi @TwistyPop we fixed this issue with PR #117
