### ISSUE TITLE
How can I get value of key up event on chosen select?

### ISSUE THREAD

**Issue by HayotIsmatov** [leocaseiro/angular-chosen#135]
I'm using angular chosen select, which is named localytics.directives module, and I want to set a key up event into this select input,How can I get this value?Thanks!

    <select chosen
                  ng-change="vm.fixItem(matchedLevel,unresolved)"
                  disable-search="false"
                  ng-model="matchedLevel"
                  ng-options="matchedLevel as matchedLevel.Name for
                  matchedLevel in level.allLevelItems">
      </select>

**Comment by leocaseiro** [comment]
Hi @HayotIsmatov, We've added Create Item to [v1.3.0](http://leocaseiro.github.io/angular-chosen/#create-new-item) You can, then get those values from add option. Would that be enough to you?

**Comment by leocaseiro** [comment]
I'll close this issue as I believe the [Create Item feature](http://leocaseiro.github.io/angular-chosen/#create-new-item) solved this issue
