### ISSUE TITLE
Error on last item selection

### ISSUE THREAD

**Issue by harsh5400** [leocaseiro/angular-chosen#138]
Hi 

When I select last item on second time. It is giving an error "Uncaught TypeError: Cannot set property 'selected' of undefined" on every chosen.

Regards
Harsh

**Comment by simison** [comment]
Tested, not here. What's your setup / Angular version etc? Got some code to reproduce?

**Comment by harsh5400** [comment]
Hi Simison 

Thanks for reply.

Angular version : 1.4.5
chosen version : 1.8.0

I couldn't upload the file so I writing the code here. I am getting error. 
My Controller

.controller('RootController', function ($scope) {
       		$scope.Items = [
							{SID:1, Description:"India"},
							{SID:2, Description:"Dubai"},
							{SID:3, Description:"Singapoor"},
							{SID:4, Description:"UK"}
						];
	
    });

Html code:

<select chosen   data-placeholder="Select an Option"
                                                    no-results-text="'Tough luck'"
                                                    ng-model="dataMod"
                                                    ng-options="Item.SID as Item.Description for Item in Items"       s     style="width:200px;"
                                                    
                                                    allow-single-deselect="true"
                                                    name="{{field.name}}"
                                              ></select>	
												Selected Item:	{{dataMod}}

**Comment by miqmago** [comment]
Same problem here. It seems the error is a little bit deeper: it selects the next option from the selected one:

```html
<select name="country" class="form-control ng-untouched ng-valid localytics-chosen ng-valid-required ng-dirty ng-valid-parse" chosen="" data-placeholder="Country" ng-options="country as country.name for country in model.countries" ng-change="onCountryChanged()" ng-model="model.country" required="" style="display: none;">
  <option value="object:17" label="Afghanistan">Afghanistan</option>
  <option value="object:18" label="Åland Islands">Åland Islands</option>
  <option value="object:19" label="Albania">Albania</option>
...
```
When selecting Afghanistan:

```html
<div class="chosen-container chosen-container-single" style="width: 333px;" title="">
  <a class="chosen-single" tabindex="-1">
    <span>Afghanistan</span>
    <div><b></b></div>
  </a>
<div class="chosen-drop">
  <div class="chosen-search">
    <input type="text" autocomplete="off">
  </div>
  <ul class="chosen-results">
    <li class="active-result result-selected" data-option-array-index="1">Afghanistan</li>
    <li class="active-result" data-option-array-index="2">Åland Islands</li>
    <li class="active-result" data-option-array-index="3">Albania</li>
```

It seems all fine up to here, but when debugging `onCountryChanged()` (`ng-change` function), this is the result:

```javascript
$('select[name="country"]').val()
"object:18"

$('select[name="country"]').chosen().val()
"object:18"
```

So it seems that chosen is storing the next value from the selected one ("Afghanistan" is actually corresponding to `object:17`, "Åland Islands" to `object:18`)

**Comment by miqmago** [comment]
If chosen directive is removed all works fine

**Comment by luclanet** [comment]
Small work around:
Add
<option disabled></option>
at the end, nothing visible and no longer problems.

**Comment by luclanet** [comment]
Damn, but no longer bind at all.

**Comment by daksakad** [comment]
The first time an option is selected, it gets the correct value, after that it selects the next option from the selected one.

**Comment by iokube** [comment]
This issue was occurring for me when the ng-options model element size was changing. In my case, I did not have a default selected value and, if that is the case, angular auto generated a type undefined into my options list. When chosen gets built at runtime, it includes that extra option in it's calculations. Now when a value from he dropdown gets selected, angular removes the unneeded default value (undefined) and the ng-options model shrinks in size by 1. This is why all the selections after this become off by a value of 1 and the bottom choice results in an error.

I fixed my issue by injecting into my ng-options array a value of undefined but I imagine it would also be solved if a default value is selected on a build.

In regards to the plugin, I imagine there would need to be some sort of watch placed on the ng-options to determine when the option list size changed. When the size changes, call the chosen reset/rebuild (not sure on those methods) which would then rebuild the chosen dropdown with the correct and up-to-date ng-options elements.

**Comment by afhaque** [comment]
This error occurs even when ng-option is not being used. It happens in cases as simple as this one:

                            <select id="errorstatus" data-placeholder="Yes / No..." chosen class="chosen-select" ng-model="formData.errorstatus">
                                <option value=""></option>
                                <option value="true">Yes</option>
                                <option value="false">No</option>
                            </select>

**Comment by Shutterix** [comment]
I had the same problem with this behavior. I used the following as workaround:
```
  <select 
	chosen
	data-placeholder="Placeholder"
	ng-model="myValue"
	ng-options="item.name for item in itemList"
	>
	<option value=""></option>
  </select>	
  {{myValue.name}}
```

And change options:
```
$scope.itemList = ['Option1', 'Option2', 'Option3'];		
```
To:
```	
$scope.itemList = [{name: 'Option1'}, {name: 'Option2'}, {name: 'Option3'}];	
```

**Comment by Kiee** [comment]
Whilst not ideal, I found the solution to be similar as whats referenced above.

Instead of using hardcoded `<option>` use `ng-options` with 1 disabled option like so:

```
<select ng-model="model" ng-options="o as o for o in array_of_options">
  <option disabled></option>
</select>
```

**Comment by afhaque** [comment]
Appreciate the responses everyone. Glad to have ways to hack around this issue.

**Comment by yuhongcheng2003** [comment]
Add disabled to the empty option didn't work for me, but convert the hard coded options to ng-options with an array of objects worked. (also with an empty option, but didn't have to disable it)

I think this bug is similar to this one, except the suggested solution there didn't work for hard coded (inline) options.
https://github.com/localytics/angular-chosen/issues/8

**Comment by maeishoj** [comment]
the empty option approach did no work for me. my array of "choices" gets somehow shifted so if I have 

<select chosen name="riskRating" data-placeholder="Select an option" ng-model="ngDialogData.evaluation.riskRating"
ng-options="item for item in ngDialogData.riskRatings" ng-required="true"></select>
<option value=""></option>

where evaluation.riskRating is an array like so: ['high', 'medium', 'low'] 

once I click on any of the 3 choices, for example medium, the high becomes medium, medium becomes low and if I try to click (Set) low, that is of course undefined. No one has solved this yet?

**Comment by miguel4ngelc** [comment]
this works for me:

`
<option disabled></option>
`

Thanks @luclanet :)

**Comment by venkateshparihar** [comment]
Kiee  thanks it works

**Comment by leocaseiro** [comment]
Hi, is this happening still?

Could you please show me a plunkr with your example @yuhongcheng2003 ?

I would go with ng-options and an empty <option> as well, like @Kiee said.


```html
<select chosen ng-model="model" ng-options="s for s in states">
       <option disabled></option>
 </select>
```

Like here: http://plnkr.co/edit/1U8KCH?p=preview

**Comment by leocaseiro** [comment]
btw, is your list quite big? Would that PR #64 fix your issue?

**Comment by lpsBetty** [comment]
This should solve the problem: 

- add an empty `<option></option>` (no `disabled` required) inside the select 

Here is **why**:
https://docs.angularjs.org/api/ng/directive/select

> If the viewValue of ngModel does not match any of the options, then the control will automatically add an "unknown" option, which it then removes when the mismatch is resolved.
> 
> Optionally, a single hard-coded <option> element, with the value set to an empty string, can be nested into the <select> element. This element will then represent the null or "not selected" option.
