### ISSUE TITLE
add edit and new button

### ISSUE THREAD

**Issue by cina2012** [leocaseiro/angular-chosen#140]
hi.
tnx for nice work.
i have a problem:
i want to add edit button to each row (option)  and add New button (for insert option) to bellow chosen-drop.
and when user clicked each button, trigger a function in angular controller.

**Comment by leocaseiro** [comment]
Hi @cina2012 we've added Add item on [v1.3.0](http://leocaseiro.github.io/angular-chosen/#create-new-item)
