### ISSUE TITLE
Use with angular.element breaks events when called on hidden select field

### ISSUE THREAD

**Issue by rodriguezrs** [leocaseiro/angular-chosen#142]
I am including all scripts in the HTML file in order of precedence as defined in the documentation.

For information:
```javascript
angular.element(document.querySelector('select')).trigger('chosen:updated');
```
does not work when the chosen is initialized on a hidden select input.  However:
```javascript
$('select').trigger('chosen:updated');
```
works just fine.

It's interesting in the fact that angular should be using jQuery in this aspect, but there is some idiosyncrasy that's causing unexpected behavior.

**Comment by leocaseiro** [comment]
Hi @rodriguezrs, please make sure you load jQuery before angular, otherwise, Angular jQlite will try do the job.

Let me know if work. Thanks

**Comment by rodriguezrs** [comment]
Hello, thanks for your response. I am loading jQuery before angular, sorry that I wasn't clear in my original message.

**Comment by leocaseiro** [comment]
I have a new realease to publish that forces the jQuery lite while using chosen from the PR #88 which is already merge into master.

What version version of angular-chosen are you using?

Is there any chances of show me what are you trying to achieve in a plunkr/jsfiddle (ish)?

So you have a hidden select which doesn't work with Angular Chosen, right?

**Comment by leocaseiro** [comment]
Hi @rodriguezrs I have an example using `ng-if` to show/hide a `<select>` and it's working fine. I'm even using a remote $http request. Check it out: http://leocaseiro.github.io/angular-chosen/#ng-if-instead-of-ng-show-ng-hide-example

**Comment by leocaseiro** [comment]
Hi @rodriguezrs, I was wondering if this issue still happening. Did you come with a solution for that?
Thanks
