### ISSUE TITLE
ng-change and ng-show not working with Angular Chosen

### ISSUE THREAD

**Issue by afhaque** [leocaseiro/angular-chosen#145]
Trying to create a simple experiment with ng-change and ng-show. 

Using a select box to control what other divs are shown or hidden. So long as I include the "chosen" directive the below example does not work. (Once I remove the chosen directive, it works as expected).

```html
<div class="form-group">
    <label for="errorstatus">Was an error experienced?</label>
    <select id="errorstatus" ng-change="checkError()" data-placeholder="Yes / No..." chosen class="chosen-select" ng-model="formData.errorstatus" ng-options="o.value as o.alias for o in options.yesno" >
    </select>
</div>

<div class="form-group" ng-show="formData.errorstatus==true">
    <label for="errorDetails">Describe the error in detail:</label>
    <textarea  rows="3" class="form-control" id="errorDetails" placeholder=" " ng-model="formData.errordetails"></textarea>
</div>	
```
Controller Function

```javascript
$scope.checkError = function(){
    if($scope.formData.errorstatus)
    {
        console.log("TRUE");
        $scope.errorTrue = true;
    }
    else
    {
        console.log("FALSE");
        $scope.errorTrue = false;
    }
};
```

**Comment by afhaque** [comment]
I should point out this issue only takes place if a user attempts to switch back and forth between options more than 2 times. (First two times, it works correctly. Third time onward it fails. The only way around this is to enable single_deselect mode and then to have the user manually hit the x").

**Comment by leocaseiro** [comment]
Can you use $scope.$watch instead of ng-change?

Similar to #119 ?
http://plnkr.co/edit/DuFbSh?p=preview

**Comment by leocaseiro** [comment]
> Instead of `ng-show` and `ng-hide` you must use `ng-if`

> Instead of `ng-change`, you must use `ng-model` and `$scope.$watch`

Read Docs for more info: http://leocaseiro.github.io/angular-chosen/

**Comment by leocaseiro** [comment]
Need to update docs about that, actually, Also create a plunkr example.

**Comment by leocaseiro** [comment]
Thanks @lpsBetty 

I also found [this](http://www.codelord.net/2015/06/11/using-ng-change-instead-of-$watch-in-angular/)

By the way, actually `ng-change` works well: http://plnkr.co/edit/UYyOVw?p=preview

**Comment by lpsBetty** [comment]
So you can close this issue?
