### ISSUE TITLE
Chosen Input Boxes Extend Past Panel

### ISSUE THREAD

**Issue by afhaque** [leocaseiro/angular-chosen#146]
Right now if you include a chosen select box inside of a Bootstrap panel it extends past the width of the panel (on smaller screens).

![image](https://cloud.githubusercontent.com/assets/5855843/11475629/5bb310fc-974c-11e5-8981-a066509e2f39.png)

**Comment by leocaseiro** [comment]
If you set the width to 100% works for you?

```html
<select chosen width="'100%'">...</select>
```

**Comment by DrowningElysium** [comment]
I am having this bug too. But it seems the `width="'100%'"` works

**Comment by leocaseiro** [comment]
Thanks! I'll close this issue, if @afhaque would like to keep open, let me know! Thanks
