### ISSUE TITLE
static data-placeholder

### ISSUE THREAD

**Issue by ekarudianto** [leocaseiro/angular-chosen#147]
I'm building an app using angularjs and this component as the select boxes.. on my app, there is an internationalization mode where user could change the language of the UI..

then I noticed if I translate it the data-placholder were updated statically not according to the $scope changes. this is the chosen element codes that I implemented, note that this is just an example

```html

<select ng-model="example" data-placeholder="{{lang.selectbox}}">
   <option value="">
</select>

```

this is the translation process

```javascript

$scope.translate = function() {
  $http.get("translate.json").success(function(result) {
     $scope.lang = result
  });
}

```

is there a way to trigger the data-placeholder model changes ?

**Comment by leocaseiro** [comment]
Check some answers on issue #121 that will help you.
