### ISSUE TITLE
Get user typed text

### ISSUE THREAD

**Issue by niktrix** [leocaseiro/angular-chosen#148]
Is there any way to get the text typed by user, I want to query database according to user typed text

**Comment by adamsh25** [comment]
Hi, I would like to know, if there is any chance to get an input from the user, inside the already filled select directive?
* the value that the user insert has not been found in the select options.

**Comment by leocaseiro** [comment]
If you use *ng-model*, you can watch with ```$scope.$watch```, like so:

HTML
```html
<select chosen ng-model="state" ng-options="s for s in states">...</select>
````

JS
```javascript
.controller('MyCtrl', function($scope) {
     $scope.$watch('state', function(typeByUser) {
         console.log('typeByUser', typeByUser);
    });
});

Plunkr demo: http://plnkr.co/edit/DuFbSh?p=preview

**Comment by leocaseiro** [comment]
I'll check it for you. That's interesting...

**Comment by leocaseiro** [comment]
This is related to #104

**Comment by leocaseiro** [comment]
I've being trying to make it work, but no rally lucky.

I believe this https://github.com/harvesthq/chosen/pull/166 would be nice, but chosen team don't want to accept.

I was wondering, if you try to use his Chosen instead, would work for you?
https://github.com/koenpunt/chosen

I'll try work on this feature later on.

**Comment by leocaseiro** [comment]
Hi @niktrix and @adamsh25, I've come with a solution you can find [here](https://github.com/leocaseiro/angular-chosen/issues/112#issuecomment-195817574) at #112
