### ISSUE TITLE
Fix chosen dependency on bower.json

### ISSUE THREAD

**Issue by sovanna** [leocaseiro/angular-chosen#149]
got this message when I try to bower install ,
said that about "chosen",
anybody got ideas ?

thx

**Comment by chinchang** [comment]
+1

**Comment by sovanna** [comment]
actually, I think that its due to node version with its lib to decompress lib zip which make this error.
as it cannot decompress, I fork the repo, and update the location of "chosen",

you can add this in your bower.son
"angular-chosen-localytics": "git@github.com:sovanna/angular-chosen.git#~1.0.10"

basically, I change the location of "chosen" which point now to the "harvesthq" bower-chose where it has to be.

**Comment by MangeshPimpalkar** [comment]
+1
