### ISSUE TITLE
allow-single-deselect="true" and model

### ISSUE THREAD

**Issue by rseiffert** [leocaseiro/angular-chosen#151]
1) Use allow-single-deselect
2) Select an option
3) Deselect that option again
Expected result: The corresponding model should be undefined
Actual result: The corresponding model grabs the first element of the array of options, but does not show this in the select field

**Comment by Morteza1360** [comment]
1+

**Comment by leocaseiro** [comment]
This issue is similar to #38 #40 #92, could you please show me in a plunkr?

Here's a plunkr start: http://plnkr.co/edit/1U8KCH?p=preview

**Comment by rseiffert** [comment]
Sometimes it is worth to read the docs, twice.... This only happens if you do not use an empty option:
Bad example, without an empty option tag: http://plnkr.co/edit/B1HFf8lAzo7BclkBiDgU?p=preview 
Good example, with an empty option: http://plnkr.co/edit/2AWk44fI31tBlUF4d3T8?p=preview

So, I do have to apologize and close this

**Comment by leocaseiro** [comment]
Thanks for that! I'm glad it worked out
