### ISSUE TITLE
Chosen Multiple not working when ng-model is null

### ISSUE THREAD

**Issue by vishnurs** [leocaseiro/angular-chosen#152]
Hi

Chosen multiple is not working if the ng-model value is undefined or null

```
<select chosen multiple ng-options="item as item for item in locations"
ng-model="myLocation">
<option value=""></option>
</select>
```

When I read the documentation, it is mentioned that

>if your ngModel is null or undefined, you must manually include an empty option inside your select, otherwise you'll encounter strange off-by-one errors:

So I added `<option>` but still it is not working. When I define `myLocation` with a value in locations, it is working perfectly.

This is happening only with chosen multiple. When I debugged the html, I could see `ul chose-results` has not `li` elements

```
<div class="chosen-drop">
<ul class="chosen-results"></ul>
</div>
```

Thanks

**Comment by leocaseiro** [comment]
Could you please show me on Plunkr?

It works for me http://plnkr.co/edit/6dshj8?p=preview

**Comment by leocaseiro** [comment]
Hi @vishnurs did you fix your issue?
