### ISSUE TITLE
no-results-text with button

### ISSUE THREAD

**Issue by rajaram-monday** [leocaseiro/angular-chosen#154]
I need to add the searched content in to the list,if the searched value  not in list.
In no-result-text i'm able to insert the input element,but ng-click function in that element is not working.

This the screenshot after searching for the not listed item with button:
![untitled](https://cloud.githubusercontent.com/assets/16758907/12391825/8e5fc050-be10-11e5-88e2-a1dab42d892c.png)

##### Controller:
$scope.noResultsText =" '\<input id=\"BtnId\" type=\"button\" value=\"add\" ng-click=\"ClickFunction(searchValue)\" /\>' " 

$scope.ClickFunction=function(searchValue){
alert(searchValue);
}

**Comment by leocaseiro** [comment]
Hi, @rajaram-monday thanks you for you question, could you please send me a plunkr from your tests and I'll try to fix there for you? I'm not sure how do you create this button, I haven't done it.
Thanks.

You can fork this plunkr to help you: http://plnkr.co/edit/1U8KCH?p=preview

**Comment by leocaseiro** [comment]
Hi @rajaram-monday I've come with a solution you can find here at #112
