### ISSUE TITLE
Add Jasmine units tests

### ISSUE THREAD

**Issue by kfarst** [leocaseiro/angular-chosen#166]
@leocaseiro I was thinking about writing some unit tests for the directive, are you open to PRs for that?

**Comment by leocaseiro** [comment]
Absolutelly, that would be awesome.
Unit testing it's on my list on issue #165

I normally use Karma to run with gulp, but I'm open for suggestions.

**Comment by lpsBetty** [comment]
oh, I just read this issue - I created some basic unit tests in the `chosen_update` branch,
PR: https://github.com/leocaseiro/angular-chosen/pull/175

**Comment by lpsBetty** [comment]
@kfarst please feel free to write more tests ;)

**Comment by leocaseiro** [comment]
Wouldn't be better include the npm libraries instead of bower libraries?

Why would I install bower only for testing if I already did with npm?

**Comment by lpsBetty** [comment]
yes that would be a better idea! I can change that, should I change that now, because when using npm we would use and old version for the tests

**Comment by leocaseiro** [comment]
Yeah, no problem! Unless we're testing any new feature of Chosen...
