### ISSUE TITLE
Problem with using service

### ISSUE THREAD

**Issue by wilrek** [leocaseiro/angular-chosen#167]
Hi, when i try to populate data asyc using webservice.
The list doesnt populate
frontend html
<select chosen="" multiple="multiple" data-ng-model="data.Tags" ng-options=" s.term_taxonomy_id as s.name  for s in Tags  " class="chosen-select form-control">
</select>

backend angularjs 
termsService.getAllTerms().then(function(p){
            $scope.Tags = p.Terms;
});

this is my first question.
Second question, if the  data is retrieved by service as well , 
even if model has some values, chosen doesnt shown up preselected value as well.

**Comment by leocaseiro** [comment]
Hi @wilrek,

You can use `ng-model` and `ng-options`. On the success of your request, you can update the values of your ng-options

```javascript
  //IDs 2 and 3 for example
  $scope.selectedItems = [2, 3];

  $scope.options = [];
  
  
  //Remote items
  $http({
      method: 'get',
      url: 'http://jsonplaceholder.typicode.com/posts'
  }).success(function(posts) {
      console.log(posts);
      $scope.options = posts;
  });
```

```html
<select ng-options="opt.id as opt.title for opt in options"
    ng-model="selectedItems" chosen multiple>
     <option value=""></option>
</select>
```

I have a plunkr that shows exactly how would work as my example:

http://plnkr.co/edit/cQEB5T?p=preview

Let me know if works for you.

**Comment by wilrek** [comment]
i think the problem is depends on whether rendering control or get data take longer.

**Comment by leocaseiro** [comment]
Sorry, I misunderstood. Would you like to explain in more details about your scenario?
A example or plunkr for me would be perfect!
Thanks

**Comment by leocaseiro** [comment]
Hi @wilrek, I was wondering if you came up with a solution for this issue.

**Comment by leocaseiro** [comment]
???? @wilrek
