### ISSUE TITLE
is there max-selection option?

### ISSUE THREAD

**Issue by choiks14** [leocaseiro/angular-chosen#174]
i want to limit selection item..

how can i?

**Comment by leocaseiro** [comment]
Hi @choiks14, thank you for your question.

By default, Chosen comes with the option `max_selected_options" which would be `max-selected-options ` in Angular Chosen, like so:

```html
<select chosen max-selected-options="3">...</select>
```

Or dynamically:

###.html

```javascript````
$scope.limit = 3;
```

###.html

```html
<select chosen max-selected-options="{{limit}}">...</select>
```

Here is an example working:

http://plnkr.co/edit/r0WAiJ?p=preview

**Comment by choiks14** [comment]
thank you :+1:

**Comment by leocaseiro** [comment]
:+1: :beers:

**Comment by awaisayub149** [comment]
I want to set max-selected-options dynamically, when product quantity change, should change max-selected-options.
