### ISSUE TITLE
'ng-disabled' is not working.

### ISSUE THREAD

**Issue by choiks14** [leocaseiro/angular-chosen#176]
html 
```
<select name="language" chosen multiple class="form-control " required 
   ng-options="type as type for type in companyTypes " 
   ng-model="me.company.type" ng-disabled="true">
</select>
```

![2016-03-14 16 43 15](https://cloud.githubusercontent.com/assets/13622941/13737863/e11f2596-ea03-11e5-95ae-9f4eac6e1135.png)

how can i?

**Comment by choiks14** [comment]
sorry it worked..  
 i did upgrade version 1.2.0 > 1.3.0.

it worked.. so sorry 

![2016-03-14 16 47 31](https://cloud.githubusercontent.com/assets/13622941/13737939/76ef401a-ea04-11e5-9d9a-9c24a06e5109.png)

**Comment by leocaseiro** [comment]
:beers: np
