### ISSUE TITLE
Get the remote data source while inputing some keywords

### ISSUE THREAD

**Issue by inarol** [leocaseiro/angular-chosen#180]
Hello,Leocaseiro.It's supported?

**Comment by leocaseiro** [comment]
Sorry, Chosen by default doesn't work with ajax search. Only if you load all your data before "chosen it"

There's an [issue](https://github.com/harvesthq/chosen/issues/79) on their repo since 2011 that still not done 

I haven't tested yet, but I found some alternatives that might work for you.

https://github.com/meltingice/ajax-chosen which I'm not sure if has been maintaned.

Also, you could try implemente with [source](https://github.com/harvesthq/chosen/issues/79#issuecomment-140774342)

**Comment by leocaseiro** [comment]
Similar to #104

**Comment by RodolpheNivelet** [comment]
Hello, do you think you could put some kind of method attribute like : 
`<select chosen on-search="ajaxPipe()"></select>`
In a way that we could have an event triggered when the user searches into the chosen search bar ?

That way we could do our own pipe ajax request and search and implement the result in the select.

Thank you,
Rodolphe

**Comment by leocaseiro** [comment]
Hi @RodolpheNivelet,
I'll probably make sure that Angular Chosen works with [Ajax Chosen](https://github.com/meltingice/ajax-chosen) at some point, but as not a chosen default feature, is not my priority at the time.

I'm happy to accept PRs, if you are keen to help.

**Comment by cgatesman** [comment]
> I'll probably make sure that Angular Chosen works with Ajax Chosen at some point, but as not a chosen default feature, is not my priority at the time.

I wouldn't recommend that as a solution.  If people are using angular-chosen, most likely they are doing their Ajax with AngularJS `$http`--not with jQuery.

I think providing an `on-search` directive attribute is the more Angular way of doing it.  This would allow the controller using the directive to make the Ajax call and adjust the model for the angular-chosen.  angular-chosen just has to properly support these dynamic model changes.

**Comment by leocaseiro** [comment]
Hi @cgatesman, thanks for your opinion.

This is a angular-chosen directive, which means I do as much as I can to make sure all chosen features work properly with Angular. Ufortunatelly, this is something that the Chosen team has never implemented, why woudl I be different? 

Well, I've tried and unfortunatelly that wasn't trivial, so I left as "help wanted".

I'd love to accept your PR, if you are keen to help with that.

**Comment by cgatesman** [comment]
I have modified the angular-chosen.js with this functionality and have been using it for quite some time.  I could look into possibly porting it over to the CoffeeScript source (I don't have CoffeeScript experience) and submitting a PR.  It may not be perfect, though.

**Comment by leocaseiro** [comment]
Hi @cgatesman, thank you for your reply and assistence.

If you need help with coffescript, here's a tool that might help you http://js2.coffee/

**Comment by hotrush** [comment]
hello @cgatesman, any news?
