### ISSUE TITLE
placeholder's dont work

### ISSUE THREAD

**Issue by stringbeans** [leocaseiro/angular-chosen#181]
Using angular 1.5.1 and latest version of angular-chosen

tried defining the chosen select as so:

```
select.form-control(
    name='school'
    chosen
    ng-model='pageData.selectedSchool'
    ng-options='school.name for school in pageData.schools'
    ng-if='!isDisabled'
    required
    ng-change='pageData.selectSchool($item)'
    data-placeholder="Pick one of these"
  )
```

And the placeholder is not set to "Pick one of these". I've also tried using `placeholder-text-single` and `placeholder` attributes and they also do not work (`placeholder-text-single` actually gives an error).

**Comment by leocaseiro** [comment]
Hi @stringbeans, thank you for your request.

The correct placeholders for Chosen and Angular Chosen are:
`placeholder-text-multiple` and `placeholder-text-single`

Check our [Documentation](http://leocaseiro.github.io/angular-chosen/#translate) and an [Example](http://leocaseiro.github.io/angular-chosen/#translate24)

**Comment by leocaseiro** [comment]
Sorry I've just read your last expression: 
> And the placeholder is not set to "Pick one of these". I've also tried using placeholder-text-single and placeholder attributes and they also do not work (placeholder-text-single actually gives an error).

Could you please be more specific about your error?

That would be nice if you could fork my [plunkr](http://plnkr.co/edit/P3bWW2?p=info) and make your changes.

**Comment by leocaseiro** [comment]
My plunkr up to date with Angular Chosen 1.3.0 and Angular 1.5.1: http://plnkr.co/edit/EW2j9r?p=preview

Tested up to multiple and single

**Comment by stringbeans** [comment]
@leocaseiro thanks for the speedy response! i looked at your plunkr and noticed that i'm setting the attribute wrong. instead of `placeholder-text-single='hello there'` it should be `placeholder-text-single="'hello there'"`

this was not reflected in the documentation and is possibly why i was confused. if you're up for it i can do a pull request on your docs to update this. 

btw, we are also a techstars company, so hi!

**Comment by leocaseiro** [comment]
Yeah! This because those string attributes emulating a scope type ['@'](https://egghead.io/lessons/angularjs-isolate-scope-attribute-binding)
With that said, you could have a variable to bind on your placeholder:

```javascript
$scope.customPlaceholder: 'My message';
```

```html
<select chosen placeholder-text-single="customPlaceholder">...</select>
```

PR are always welcome. We use [slate](https://github.com/leocaseiro/angular-chosen/issues/165#issuecomment-193958583) on docs branch.

Send me a PR there. That would be nice refer the [egghead](https://egghead.io/lessons/angularjs-isolate-scope-attribute-binding) link.
