### ISSUE TITLE
Not fully functional on touch enabled devices (iPad)

### ISSUE THREAD

**Issue by chrisjmartini** [leocaseiro/angular-chosen#188]
Tested on an iPad Air (iOS 9.3):

In testing the multiselect example at: http://adityasharat.github.io/angular-chosen/, two issues arise:

1. When the select dropdown is in focus, you can only tap one option to select at a time. To select additional options, you must close the dropdown and lose focus, then focus again to select another option.

2. When the select dropdown is open, you are unable to scroll through options list with the usual finger swipe.

However, the above does not prevent the user from making selections if they know what they are looking for. The type ahead search and select via the on screen keyboard works fine.

**Comment by leocaseiro** [comment]
Hi @chrisjmartini, 
First of all, I'm sorry, but it seems you are referring to another lib, You probably opened an issue at the wrong repo.

Well, even though it's another lib, I'm almost sure that this is a chosen well known [issue](https://github.com/harvesthq/chosen/issues/2289) with their library by itself.

You should follow this issue...

**Comment by chrisjmartini** [comment]
My Apologies! Someone sent me both the github a demo page links and it looks like they confused the two.
