### ISSUE TITLE
Select element "flickers" on first page load

### ISSUE THREAD

**Issue by boeserwolf** [leocaseiro/angular-chosen#189]
The use of $timeout (angular-chosen.js, line 72, see below) postpones the initialization of the chosen plugin to a later digest cycle. Because of that, the plain HTML select element will be painted first, leading to an ugly "flickering effect".
```
             $timeout(function() {
                chosen = element.chosen(options).data('chosen');
              });
```
Another approach to make sure the DOM is ready (without flickering) would be the default jQuery way:
```
              $(document).ready(function () {
                chosen = element.chosen(options).data('chosen');
              });
```

**Comment by leocaseiro** [comment]
Hi @boeserwolf, thanks for reporting your issue.

`$timeout` is the way that Angular handles DOM Ready. Also it's on core, so it's the only way(until now) to work with `ng-hide`, `tabs` and os on.

I'm not sure how could I fix this issue to you and unfortunately using `$(document).ready()` inside an angular-directive is not really a good solution.

I'm open to PR if you'd like to help. I'll set as **enhancement** and **help-wanted** for now.

**Comment by mehmetenes** [comment]
Hi, struggling with the same issue here. I tried using ng-hide for a timeout period but this causes multiple select chosen content to be empty. When I disable the ng-hide, while the page loads a standard html multi-select input renders for moment and then the directive converts it to chosen style multi-select (bootstrap style input). Working on a workaround and I'm open for any suggestions.

**Comment by boeserwolf** [comment]
@mehmetenes Here's a gist to a patched version of the directive I use in my project for now:
https://gist.github.com/boeserwolf/e3f42a0e476fbc8869e44aa58ccd5e08

As mentioned above, I solved the issue by using angular.element(document).ready() inside the link function. So the chosen plugin will be initialized as soon as the DOM becomes ready, which works like a charm.

@leocaseiro I'm don't think that using angular.element(document).ready() inside the link function is a really bad solution. $timeout() ensures element.chosen() get's called after the DOM was rendered. What we really want, is to apply element.chosen() as soon the DOM is available.

Just digged into the angular source: $timeout() wraps the callback in a try-catch construct, gives you control whether to call $rootScope.apply() and returns a nifty promise. The "flickering issue" remained if you'd use window.setTimeout() instead, because element.chosen() needs to be applied when the DOM becomes ready, not rendered. But I may be totally wrong. :)

**Comment by mehmetenes** [comment]
@boeserwolf thanks for the solutions. I've tried and it solves the flickering issue. 
@leocaseiro,  sorry if I couldn't make myself clear.

**Comment by leocaseiro** [comment]
Hi, @boeserwolf, could you please send me a PR? I'd like to run my tests, if they all pass, I'd be very happy to switch from $timeout to $.ready()

Thanks

@mehmetenes, I apologise for any misunderstanding.

**Comment by leocaseiro** [comment]
Hi @boeserwolf. I've seen your code and it worked for me, however, most of the tests are failing.

I've tried to setup something nice, but I'll have to change all tests to approve this PR.

Thanls for that, btw.

**Comment by boeserwolf** [comment]
Hi @leocaseiro, thanks for your quick reply. I've updated the tests as well.
