### ISSUE TITLE
Multiple select with links and second field

### ISSUE THREAD

**Issue by seandcoleman** [leocaseiro/angular-chosen#190]
I am trying to make a drop down that has id's but when selected it shows:

     id: description  x

and it is a clickable link.  Is there any way to do this?

current code:
                        <select chosen
                              multiple
                              ng-model="bp.entitlements.id"
                              ng-options="i.id for i in item">
                              <option value=""></option>
                          </select>

Thank you

**Comment by leocaseiro** [comment]
You can use $scope.$watch for it or ng-change.

##### `$scope.$watch` example http://plnkr.co/edit/DuFbSh?p=preview

```javascript
$scope.$watch('bp.entitlements.id', function(changed) {
    console.log('bp.entitlements.id changed to ', changed);
    window.location.href = 'url.com';
});
```


##### `ng-change` example 

```html
<select ng-change="changeFunction()" multiple ng-model="bp.entitlements.id" ng-options="i.id for i in item">
```

```javascript
$scope.changeFunction = function() {
    console.log('bp.entitlements.id changed to ', bp.entitlements.id);
    window.location.href = 'url.com';
}
```

**Comment by seandcoleman** [comment]
Thank you for the response.  I was looking for more of the id: description display with it being clickable like it was an anchor tag.  With the standard x next to it to remove.  I tried the watch and it just redirects the whole page automatically.

<a href="url"> id1: description1 </a>    x
<a href="url"> id2: description2  </a>    x
<list of options not selected>

Is there a way to customize the output of the selected items?

**Comment by leocaseiro** [comment]
Hi @seandcoleman, could you please show me a plunkr what exactly you're expecting?

If you want to have a list of links, why don't you use only a list with ng-repeat?

```html
<li ng-repeat="i in item">
    <a>id{{i.id}}: {{i.description}}</a> <button ng-click="remove(i)">x</button>
</li>
```

Otherwise, you can always use CSS to customize your layout

**Comment by seandcoleman** [comment]
Thank you for the response.  I was able to get it to do most everything with:

```sh 
  ng-options="e.id +': ' +  e.description for e  in bp.entitlements"
```


Thanks again.
