### ISSUE TITLE
Module 'localytics.directives' is not available!

### ISSUE THREAD

**Issue by DamodarSojka** [leocaseiro/angular-chosen#191]
Hi

I am using angular-chosen with bower and grunt. After minification I am getting Module 'localytics.directives' is not available! error.

I know about renaming chosen.jquery.js to chosen.js

This is how things are looking in index.html

<script src="lib/chosen/chosen.js"></script>
<script src="lib/angular-chosen-localytics/dist/angular-chosen.js"></script>

Any ideas what is wrong?

**Comment by leocaseiro** [comment]
Hi, does it work without minification?
If it does, you must inject all your modules as strings with inline annotation, like you can find in the follow article: https://scotch.io/tutorials/declaring-angularjs-modules-for-minification

**Comment by leocaseiro** [comment]
Hi, would you mind showing me a plunkr or similar to see your `minified.js`?

If you remove the minification, it works?

**Comment by DamodarSojka** [comment]
Thanks for a very quick reply. 
It works if I remove the minification, 

I have included both minified scripts and vendor scripts:
https://plnkr.co/edit/15mCbkRO70r7nH65Wtjv?p=catalogue

**Comment by leocaseiro** [comment]
Hi @DamodarSojka, I've tried to access this plunker, but it's empty. Please, make sure you Save to publish or Fork to public Plunk

**Comment by DamodarSojka** [comment]
Sorry for that, I have not used plunkr before. Is this one working?

https://plnkr.co/edit/VOwfKUXB54EHZKQ5oSbE?p=catalogue

**Comment by leocaseiro** [comment]
Your application is good, could you also add your bower files?

**Comment by DamodarSojka** [comment]
https://plnkr.co/edit/UVXmnh0CdukmfEaZaLdn?p=catalogue

**Comment by leocaseiro** [comment]
Hi @DamodarSojka, I'm getting the error:
 `vendor.js:19 Uncaught TypeError: Cannot read property 'plugins' of undefined`

I believe you must fix it before check what is wrong with Angular Chosen...

Also if you remove the Dependency `"localytics.directives"`, you get a infinite loop with Alerts:
`$stateChangeError [object Object`

Also it seems redirecting to `/login` and something else...than locks my Browser...

**Comment by leocaseiro** [comment]
Did you get the same error?

**Comment by DamodarSojka** [comment]
I have just solved it few minutes ago, the problem was related to the order in which I was loading Flot libraries, once the order was changed everything started to work. Thanks for help! By the way I never got the Cannot read property 'plugins' of undefined error.

**Comment by leocaseiro** [comment]
No worries, thanks for your feedback :smile: :beers:
