### ISSUE TITLE
The input selector is not shown

### ISSUE THREAD

**Issue by 1izpena** [leocaseiro/angular-chosen#192]
I wrote this:
```html
<select chosen multiple options="githubrepositories"
                    ng-model="repositorySelected"
                    ng-options="p.name as p.name for p in githubrepositories">
 </select>
```
inside the bootstrap modal.
But in the console, appears width 0px and the input of selector not shown. It isn't your css or mine. I don't know what happens. Any idea?
Thank you very much.
![selectorerror](https://cloud.githubusercontent.com/assets/5814411/14389077/3709d7ec-fdb1-11e5-80d0-7c79d2594ab8.png)

**Comment by leocaseiro** [comment]
Hi @1izpena,

Try with `width="'100%'"`:

```html
<select width="'100%'" chosen multiple options="githubrepositories"
                    ng-model="repositorySelected"
                    ng-options="p.name as p.name for p in githubrepositories">
 </select>
```

**Comment by 1izpena** [comment]
Hi @leocaseiro, it doesn't work. Thanks anyway.

**Comment by leocaseiro** [comment]
Hi @1izpena, what happens if you remove `chosen` directive?

Could you also try use css?

```css
select {
     width:500px"
}

````

Or perhaps harcoded style: 
<select style="width:500px" chosen multiple options="githubrepositories"
                    ng-model="repositorySelected"
                    ng-options="p.name as p.name for p in githubrepositories">
 </select>

**Comment by leocaseiro** [comment]
Did it work?

**Comment by 1izpena** [comment]
No, I am sorry. In the end I had to take another library. Thanks anyway.
