### ISSUE TITLE
ngModelOptions not working

### ISSUE THREAD

**Issue by ganeshkantu** [leocaseiro/angular-chosen#193]
Is ngModelOptions supported with this module? I am trying to use a getter/setter and the value never gets passed. Anyone know a way of getting this to work?

**Comment by leocaseiro** [comment]
Hi @ganeshkantu, thanks for your issue.

I'm not sure exactly what you want to achieve here, but if you could show me an example (plunkr/jsfiddle/etc) without chosen in a simple select, I could, perhaps see how would it work with angular chosen.

**Comment by ganeshkantu** [comment]
@leocaseiro 
This is what I have for a simple select:
```
<select ng-model="getSetChosen" ng-model-options="{ getterSetter: true }" ng-options="c.value as c.text for c in countries">
  <option value=""></option>
</select>

$scope.getSetChosen = function (value) {
   ...
};
```

This works. But when I try with angular chosen, the `getSetChosen` is never called. You mention that this module is compatible with Angular 1.2+ - I believe getter/setter was introduced in 1.3. Could that be an issue?

**Comment by leocaseiro** [comment]
Hi @ganeshkantu, sorry for my delay, I actually thought I had answered this.

So, this library is compatible with Angular 1.5.3 and that's the version I'm testing in our demos.
I'm not sure about getterSetter. I've never used it. I actually never had a case that I needed to.

Would not a ng-model as function supply your needs?

**Comment by leocaseiro** [comment]
ping @ganeshkantu
