### ISSUE TITLE
Chosen not work on iPhone 5 with over 2000+ options

### ISSUE THREAD

**Issue by BraveVN** [leocaseiro/angular-chosen#194]
I'm using Angular Chosen with thousands of options, it works good on desktop and iPad but on my iPhone 5, I cannot search ! It's terrible to scroll in 2500 options to choose 1.
The second, I tried to set the limit of selection to 2 options, it works well on desktop and iPad but on iPhone, I can choose as many as I want, there's no limit.
Please optimize it.

**Comment by simison** [comment]
Could you post a Plunker/JSFiddle and tell us the iOS version?

**Comment by leocaseiro** [comment]
Related with #156 as well. A side way would be working with a remote engine.

2500 options without remote is really not a friendly way to implement even on a desktop.

I suggest you choose one of those solutions:

1. Try implement the remotely as we mention at #104 and #180 
2. Try another select ui that get's Ajax as [Angular Material Select](https://material.angularjs.org/latest/demo/select), [Selectize](http://selectize.github.io/selectize.js/), [Angular Ui Select](http://stackoverflow.com/a/26061904/3415716)

**Comment by BraveVN** [comment]
@simison I'm sorry but I cannot put it on Plunker or JSFiddle, it's company's stuffs. Currently, I'm using the iPhone 5 with iOS 9.3.1
@leocaseiro Thanks for your suggest, remote data is a great idea, but I think I will try to implement another library.

**Comment by leocaseiro** [comment]
@BraveVN I wish Chosen has [accepted the Ajax request](https://github.com/harvesthq/chosen/issues/79) long time ago...

I'll try implement https://github.com/ksykulev/chosen-ajax-addition or https://github.com/meltingice/ajax-chosen. 

That's the 3rd issue about it and I don't want to repeat their "mistake"

**Comment by leocaseiro** [comment]
PS: another alternative is [select2](https://github.com/select2/select2)

**Comment by BraveVN** [comment]
Thanks for your support, I'll close this issue

**Comment by leocaseiro** [comment]
I'd rather keep open until I implement this feature. Thanks

**Comment by leocaseiro** [comment]
Chosen should not work on iPhone anyway. Closing issue.
