### ISSUE TITLE
Custom search algorithm 

### ISSUE THREAD

**Issue by Lyubomyr** [leocaseiro/angular-chosen#197]
Hi.
I didn't found ability to change current search algorithm to my own, to make full text search (not only from word begging and using multiple words separated by space). Is some ability to do so?

**Comment by leocaseiro** [comment]
Hi @Lyubomyr,

Thank you for your Issue.

Unfortunately, Chosen doesn't work with this feature. I strongly recommend you trying something more powerful as [select2 with the Remote feature](https://select2.github.io/examples.html#data-ajax).

If you use Twitter Bootstrap, you should also have a look into [angular-ui select](https://github.com/angular-ui/ui-select)

I also like the [selectize](https://github.com/machineboy2045/angular-selectize) which is probably the most powerful of them.


Last, if you use Angular Material, try the [Autocomplete component](https://material.angularjs.org/latest/demo/autocomplete)

**Comment by Lyubomyr** [comment]
Thank you for fast response and this links!
