### ISSUE TITLE
allow-single-deselect don't set model to null

### ISSUE THREAD

**Issue by giopetris** [leocaseiro/angular-chosen#199]
The option `allow-single-deselect` don't set the model to `null` when the close icon is clicked.

**Comment by leocaseiro** [comment]
Hi @giopetris,
Thank you for using the directive and for open this issue.

The `allow-single-deselect` don't set the model `null`, but will clean your model.

I don't see why you need to set to null. You could, watch your model and set to null if it's empty, though.
