### ISSUE TITLE
Promlem on min version angular#^1.5.*

### ISSUE THREAD

**Issue by Galamoon** [leocaseiro/angular-chosen#200]
На min версии angular не обновляется model. Я сам в шоке, не знаю с чем это может быть связано, но при использовании uncompresed angular все работает отлично. 
Приложение загружается с помощью requireJS.
Проблему заметил пока только в Chrome#50.0.2661.102 m в остальных браузерах проверю завтра.

Google translate: 
On angular min version is not updated model. I am very shocked, I do not know what it can be connected, but using uncompresed angular everything works fine.
The app is loaded with the help of requireJS.
The problem is observed only in the Chrome # 50.0.2661.102 m in other browsers will check tomorrow.

**Comment by leocaseiro** [comment]
Please, send me a [plunkr](http://plnkr.co/edit/1U8KCH) with your issue and I'll analyse it.

**Comment by Galamoon** [comment]
Well over the weekend I will do, right now there is no time.

**Comment by leocaseiro** [comment]
Hi @Galamoon, is this issue is happening still?

**Comment by KryDos** [comment]
Hi, I have the same issue but it is not depend on compressed/not-compressed angular.js. 

As far as I can see the `<select> ` itself is also not updated when option is selected. I do not use requireJS and I'm on Firefox.

**Comment by leocaseiro** [comment]
Please, send me a plunkr with your issue and I'll analyse it.

**Comment by KryDos** [comment]
That's pretty strange but I can't reproduce this issue on plunkr... 
I tried to use same versions of angular/chosen/angular-chosen/jquery that I have in my project, but it still works on plunkr. 

So, it is differently something on my project side. Still trying to find what is this

**Comment by KryDos** [comment]
Found the reason, at least why it didn't work for me. Documentation on the site describes that **jquery should be included before angular** but I didn't see this and my jquery was included after. This is actually the reason. Documentation was not attentively read. Sorry about that.

**Comment by leocaseiro** [comment]
Hi @KryDos, thanks for letting me know.

Yeah, that's an angular thing. It's not exclusively for this directive.
Every time you'd like to use jQuery + AngularJS, you must include jQuery first.

Read more http://www.gjermundbjaanes.com/angular-and-jquery-load-order-matters/
