### ISSUE TITLE
Using a watch on the search filter

### ISSUE THREAD

**Issue by snaplemouton** [leocaseiro/angular-chosen#201]
A picture is worth a thousand words so here goes:
![image](https://cloud.githubusercontent.com/assets/4615537/15909064/a4dd236c-2d92-11e6-9717-aca161fb9218.png)
I want to know if what the user type in the textbox can be found in a scope or if there is any way to watch for a change on what is written inside the search.
For example, if I could find the "253" above in a scope called "foo" I'd be able to watch like this:
`$scope.$watch("foo", function (newValue) {
            doSomething();
        });`
ng-change/watching the ng-model on the select tag only get called when an item is selected or deselected in the list.
`<select chosen ng-change="foobar()" ng-model="foo" ng-options="bar for bar in bars" multiple></select>`
But what I want is to watch the change on what the user type in the search for options.

**Comment by leocaseiro** [comment]
I'm sorry, it's not possible. That's a Chosen issue and I couldn't make it happen.

Related to #104 #148

The most related solution you could use is #112
