### ISSUE TITLE
data-placeholder-text-single - clobbers all placeholders on the page

### ISSUE THREAD

**Issue by stenmuchow** [leocaseiro/angular-chosen#203]
Using data-placeholder-text-single to override the normal "select an option" text seems to clobber all placeholder texts, and also overrides any previous declared placeholder values. 

The second one overrides the first declaration..

```
<select chosen="chosenOptions"
                                    class="form-control"
                                    data-placeholder-text-single="'{[{'I am a placehlder' | translate }]}'"
                                    ng-options="option as (option.display_name | capitalize) for option in dropdown.distanceToHubOptions track by option.name"
                                    ng-model="distanceToHub"
                                    ng-change="updatePODetails(distanceToHub.name, 'distance_to_hub')">
                                <option value=""></option>
                            </select>


 <select chosen="chosenOptions"
                                    class="form-control"
                                    data-placeholder-text-single="'{[{'I am another placehlder' | translate }]}'"
                                    ng-options="option as (option.display_name | capitalize) for option in dropdown.publicTransportationOptions track by option.name"
                                    ng-model="publicTransportation"
                                    ng-change="updatePODetails(publicTransportation.name, 'public_transportation')">
                                <option value=""></option>
                            </select>
``` 

http://puu.sh/prc0M/7d55db42a0.png

**Comment by leocaseiro** [comment]
Hi @stenmuchow, thank your for using the directive and for opening an issue.


Sorry, could you please check your syntax?

It seems you have some square brackets: `{[{...}]}` mixed with your curly braces. I believe that's your error.

I have an example here working perfectly: https://plnkr.co/edit/10cRsvkn2Bop1blzEDrW?p=preview

**Comment by stenmuchow** [comment]
Its not incorrect syntax - using the $interpolationProvider its possible to override the brackets.

```
  $interpolateProvider.startSymbol('{[{');
  $interpolateProvider.endSymbol('}]}');
```

I did notice in the source you are manually checking for the string {{ so it seems that anyone manually overriding the {{ }} syntax will have errors. 

We could add a check for the startSymbol instead of hardcoding it? 

https://docs.angularjs.org/api/ng/provider/$interpolateProvider

**Comment by leocaseiro** [comment]
Hi @stenmuchow, 
Thanks for your reply.

Could you please update my plunkr with your example? I'm sorry but I'm not aware of the `$interpolationProvider`.

If you could set something similar that would work without chosen would be awesome. So I can try fix with chosen.

Thanks

**Comment by leocaseiro** [comment]
I'm, sorry @stenmuchow.
I've just realised what you meant [here](https://github.com/leocaseiro/angular-chosen/blob/master/src/chosen.coffee#L61).

Yeah, atm we do check the `'{{'`manually.
I'll probably read about [$interpolateProvider](https://docs.angularjs.org/api/ng/provider/$interpolateProvider).

If you replace manually from `{{` to `{[{` at the [`angular-chosen.js`](https://github.com/leocaseiro/angular-chosen/blob/master/dist/angular-chosen.js#L48) works for you? If does, the fix is definitely there.

**Comment by stenmuchow** [comment]
Ok I was finally able to isolate the bug.

https://plnkr.co/edit/OqshrC3dXMidVCIWvldP?p=preview

It seems that when passing chosenOptions object to the directive is when I am getting this error.

THe plukr is there. If you remove the `chosen="chosenOptions"` the bug goes away...

**Comment by leocaseiro** [comment]
Hi @stenmuchow,

I realised that. It's not related to the $interpolateProvider. I didn't even know that was possible to pass a `chosenOptions`.

Before we implement #77, unfortunately that's the way to go. You could, however, have the values as global vars.

for the width, you could use css: 

```css
    .localytics-chosen,
    .chosen-container {
        width: 100%;
    }
```

https://plnkr.co/edit/u44bgoEAU6mbDbsDB8WU?p=preview

**Comment by stenmuchow** [comment]
Yeah, ok... Legacy code I am working to maintain and extend. Will make those changes suggested... You are welcome to close the issue. Thanks again for the help!

**Comment by leocaseiro** [comment]
No worries! It's quite more work, but at least work.
