### ISSUE TITLE
'data-placeholder' does not work after adding ng-options 

### ISSUE THREAD

**Issue by pranjal-goswami** [leocaseiro/angular-chosen#205]
Chosen version : 1.6.1
angular-chosen : 1.4.0

`<select class="" chosen="{width:'100%'}" multiple data-placeholder="Recepients" ng-model="recepients">`

The 'data-placeholder' attribute works fine as long as **ng-options** is not added

`<select class="" chosen="{width:'100%'}" multiple data-placeholder="Recepients" ng-model="recepients" ng-options="contact as contact.name for contact in contactBook">`

- data-placeholder no longer works

**Comment by leocaseiro** [comment]
Hi @pranjal-goswami, thank you for using the directive and for openning an issue.

You must use the attributes: `placeholder-text-multiple` and `placeholder-text-single` instead.

Please check the example


```html
<select class="" chosen="{width:'100%'}" multiple placeholder-text-multiple="Recepients"
ng-model="recepients" ng-options="contact as contact.name for contact in contactBook">
</select>
```

**Comment by pranjal-goswami** [comment]
Hi @leocaseiro, thank you for your response. 
I tried using the suggested attributed but it did not work. I have made this [jsFiddle](https://jsfiddle.net/1n4b2Lfp/) for your perusal

**Comment by leocaseiro** [comment]
Hi @pranjal-goswami, I'm sorry, I actually forgot to mention that both placeholder-text-multiple and placeholder-text-single are expecting a bindable value, so you must use a string value or a variable:

```html
<select class="" chosen="{width:'100%'}" multiple placeholder-text-multiple="'Recepients'"
ng-model="recepients" ng-options="contact as contact.name for contact in contactBook">
</select>
```

Or dynamic:
```javascript
$scope.label = 'Recepients';
```
```html
<select class="" chosen="{width:'100%'}" multiple placeholder-text-multiple="label"
ng-model="recepients" ng-options="contact as contact.name for contact in contactBook">
</select>
```

jsfiddle updated with both examples: https://jsfiddle.net/9d8n4zsf/

**Comment by pranjal-goswami** [comment]
Thanks a lot!
