### ISSUE TITLE
multi-selection of filetered items

### ISSUE THREAD

**Issue by bgadiel** [leocaseiro/angular-chosen#206]
Hi,
I am implementing a 'Multiple Select' by passing an array of objects to ng-options.
When filtering results with a search query (e.g: typing the letter 'a'), I am trying to select all results (using 'Shift' key).
Problem is that the list is getting refreshed after every selection and the search query is deleted, therefore I need to type the query again and again after each 1 item selection.

Is there a way to be able to multi-select the filtered results?

It works great in 'Multiple Select' example in [Chosen page](https://harvesthq.github.io/chosen/).

**Comment by leocaseiro** [comment]
Hi @bgadiel, thank you for using angular-chosen.

I'm sorry, I tried to multi-select using the shift key, but it didn;'t work for me. None on angular-chosen and not even on jquery chosen.

However, it's working with the Command key(on mac) in both of them. Have you tried that?

**Comment by leocaseiro** [comment]
There's a well-known issue while selecting a big list. The list is going to the top.

Please read more at #59.

**Comment by bgadiel** [comment]
Yes, its working with the 'command' key. and Yes, I am having a big list to select from.
in 'going to the top' meaning the list is refreshed?
The behaviour that I see that if I filter 1000 results using the string 'abc', and now I have 10 items. 
I try to select all 10 items using 'command' key, but after each item selection, the list returns back to 1000 items.

**Comment by leocaseiro** [comment]
Hi @bgadiel, I've release a new version with this fix.
Could you please try the version 1.4.3?

If doesn't work, could you please create a [plunkr](https://plnkr.co/edit/4dpqKG?p=preview) for me?

**Comment by bgadiel** [comment]
Works perfectly!
Thanks.

**Comment by bgadiel** [comment]
Hi,
This issue occurs again in chosen#1.8.0. - see [here](https://plnkr.co/edit/4dpqKG?p=preview).
Short description - search for the letter 'c' and click CMD / CTRL while multi-selecting.
The list of values should all be filtered with 'c' as long as the CTRL / CMD is pressed, while in fact the list is refreshed for every selection you make.
This is not happening with chosen#1.7.0.
(I am not sure this is a bug in the angular-chosen, though).
How do I revert back to chosen#1.7.0 when reinstalling angular-chosen-localytics#1.7.0 with bower? (bower auto fetch the latest chosen version).

Thanks.

**Comment by VanTanev** [comment]
@bgadiel Per the [bower spec](https://github.com/bower/spec/blob/master/json.md#dependencies), bower uses [node-semver](https://github.com/npm/node-semver#ranges). Specifying `"angular-chosen-localytics": "1.7.0",` should resolve exactly `1.7.0`

**Comment by bgadiel** [comment]
@VanTanev , from some reason it didnt work for me, so I had to manually install chosen with bower to 1.7.0 in addition to  "angular-chosen-localytics": "1.7.0".
thanks.

**Comment by leocaseiro** [comment]
Hi @bgadiel, I'm sorry I wasn't able to reproduce your bug.

Here is a video of myself searching with the <kbd>cmd</kbd> on mac and without pressing it.
You can see on my screen video that everytime I hold the command, the list still there.

![ifwg2rrfdi](https://user-images.githubusercontent.com/940070/33153485-10e8dbf4-d036-11e7-949a-2461d3392b8a.gif)

**Comment by bgadiel** [comment]
Hi Leo,
Filter the list with 'a' prior the selection.
The list should remain filtered as long as the cmd is clicked.




בתאריך 23 בנוב׳ 2017 1:08 לפנה״צ,‏ "Leo Caseiro" <notifications@github.com>
כתב:

Hi @bgadiel <https://github.com/bgadiel>, I'm sorry I wasn't able to
reproduce your bug.

Here is a video of myself searching with the cmd on mac and without
pressing it.
You can see on my screen video that everytime I hold the command, the list
still there.

[image: ifwg2rrfdi]
<https://user-images.githubusercontent.com/940070/33153485-10e8dbf4-d036-11e7-949a-2461d3392b8a.gif>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/leocaseiro/angular-chosen/issues/206#issuecomment-346497069>,
or mute the thread

**Comment by leocaseiro** [comment]
Hi @bgadiel. Did you see my GIF?

I typed `a` holding <kbd>cmd</kbd> and it worked as expected.

![screen shot 2017-11-23 at 5 22 18 pm](https://user-images.githubusercontent.com/940070/33160745-ec931ba6-d072-11e7-8aaa-a9d21df0bfe3.png)

**Comment by bgadiel** [comment]
Oh, my plnkr was not saved.
Try with [this](https://plnkr.co/edit/hD8kLrdAwTKlfNQG8jlv?p=preview)

**Comment by leocaseiro** [comment]
Hi @bgadiel, Thanks for reporting that.

I found out that the issue is actually with the chosen library. Since chosen@1.7.0 the behaviour for command + click changed and I didn't notice.
They added a new option `hide_results_on_select` that's `true` by default.

Test yourself https://jsfiddle.net/v3kLhyu2/ 
PS: This demo is jquery chosen without angular.

This feature works great in case you don't want your users to hold <kbd>cmd</kbd> while selecting their options.

We need to open an issue on Chosen Library.


For the time being, I suggest you use an older version that [chosen@1.6.2](https://github.com/harvesthq/chosen/releases/tag/v1.6.2) that the latest library that works the way you want.

I'm almost sure it was caused by this PR https://github.com/harvesthq/chosen/pull/2867 related to https://github.com/harvesthq/chosen/issues/2809

**Comment by bgadiel** [comment]
also ver#1.7.0 of chosen was working ok.
Thanks.

בתאריך 24 בנוב׳ 2017 1:25 לפנה״צ,‏ "Leo Caseiro" <notifications@github.com>
כתב:
