### ISSUE TITLE
Chosen options with `{{` and `}}`are not processed correctly?

### ISSUE THREAD

**Issue by jeffmath** [leocaseiro/angular-chosen#208]
In version 1.4.0, line 48 of angular-chosen.js reads:

                options[snakeCase(key)] = String(element.attr(attr.$attr[key])).slice(0, 2) === '{{' ? value : scope.$eval(value);

Isn't the test on the end of the line backwards?  That is, shouldn't the $eval occur if the '{{' is present?  I had to flip the comparison to !== for my placeholder-text-single option to take hold.

**Comment by leocaseiro** [comment]
Hi @jeffmath, thanks for your issue.

Could you please be more clear about your issue? I don't understand what your mean.

The `'{{'` is present to fix #57 with the #115 since v1.1.0

Please, show me your code and tell me about your issue.

**Comment by leocaseiro** [comment]
I appreciate if you could send me a [plunkr](https://plnkr.co/edit/4dpqKG?p=preview) with your code as an example.

Actually, I think you are write. This would explain, why we need to set `''` for string values.

I'll have to investigate in deep when I have more time.

Thanks for reporting that.

**Comment by leocaseiro** [comment]
Hi @jeffmath, would you mind sending me a plunker? I'd like to investigate it deeply. Thanks

**Comment by jeffmath** [comment]
Sorry, my team is no longer using your directive, so I lack the context to be able to help you further.

**Comment by leocaseiro** [comment]
Hi @jeffmath,

No worries. Thank you for getting back to me.
