### ISSUE TITLE
ng-modal is not working when used with ng-options and group by. 

### ISSUE THREAD

**Issue by Marek00Malik** [leocaseiro/angular-chosen#209]
Hi, 
There is no modal change (I have tried using $watch to verify any modal change). 

The following code: 
```html
<select name="selectedCard" chosen class="chosen-select" style="width:250px;"
                    disable-search="true"
                    ng-if="showMultiCardNavBar()" ng-model="selectedCard" ng-change="cardSelected()"
                    ng-options="card.id as card.id group by getGroupByName(card.cardGroupId)  for card in cardsContext" >
                <option value=""></option>
            </select>
```

there is no change on this property: selectedCard. 

Had to do a workaround to query the DOM object and find the chosen-selected taged element.

**Comment by Marek00Malik** [comment]
It seems that the ng-if was the case. Moving it to a separate div resolved the issue

**Comment by leocaseiro** [comment]
Sorry, do you mean `ng-model`?

**Comment by leocaseiro** [comment]
Hi @Marek00Malik, thanks for using the library, and also for reporting this your issue!

I'll have to analyse it on the weekend. That would be easy if you could perhaps, post a [plunker](https://plnkr.co/edit/4dpqKG?p=preview) for me.

Thanks

**Comment by leocaseiro** [comment]
Hi @Marek00Malik, did you happen to get around with this issue?

**Comment by thelastinuit** [comment]
The same here @leocaseiro the ng-model is not being updated.

**Comment by leocaseiro** [comment]
Hi@thelastinuit, I'm sorry to hear that!

Would you mind making taking this plunker and making your changes?
It seems working fine for me: https://plnkr.co/edit/4dpqKG?p=preview

Thanks heaps

**Comment by thelastinuit** [comment]
Mea culpa~! 
It is something I didn't read (shame on me)!

I didn't realized that the object.selected MUST be initialized with [0] otherwise it doesn't update the selected items!

Sorry!

**Comment by leocaseiro** [comment]
Hi @thelastinuit, I'm glad you fixed your issue.

Thanks for your feedback.

**Comment by dkokic** [comment]
Hi @leocaseiro - I wonder if you could advice how to use complete objects (instead of id's) in select model. Here the example: https://plnkr.co/edit/986uGr?p=preview

**Comment by leocaseiro** [comment]
Hi @dkokic, It looks like the second <select>  is doing exactly what you're looking for:

```html
<select
      multiple
      chosen
      ng-model="stateList"
      ng-options="s as s.title group by s.country for s in states">
      <option value=""></option>
    </select>
```

**Comment by dkokic** [comment]
Yes and No ;-)
The 2nd select from https://plnkr.co/edit/986uGr?p=preview is correctly updating the model with the new selection value(s), BUT it fails to show the select model's initial values.

**Comment by leocaseiro** [comment]
Hi @dkokic,

I'm sorry I missed that. I forgot to add `track by`. In that case, it would be:



```html
<select
      multiple
      chosen
      ng-model="stateList"
      ng-options="s as s.title group by s.country for s in states track by s.id">
      <option value=""></option>
    </select>
```

https://plnkr.co/edit/qIqgEz?p=preview

**Comment by dkokic** [comment]
Thanks a million @leocaseiro

**Comment by leocaseiro** [comment]
I'm glad worked it 🍻
