### ISSUE TITLE
ng-show + select bug

### ISSUE THREAD

**Issue by jossef** [leocaseiro/angular-chosen#212]
https://plnkr.co/edit/ad6rqguvzZbrWLIGORhS?p=preview

```
  <button ng-click="toggle=!toggle">toggle: {{toggle}}</button>

  <div ng-show="toggle">
    <select chosen multiple ng-model="state" ng-options="s.id as s.title for s in states">
      <option value=""></option>
    </select>
  </div>
```

**Comment by leocaseiro** [comment]
https://github.com/leocaseiro/angular-chosen/issues/145#issuecomment-194819950

**Comment by jossef** [comment]
`ng-if` is a nice workaround but i still prefer `ng-show`

**Comment by leocaseiro** [comment]
Hi @jossef, let me know if you work around this issue. I've tried many times and I didn't succeed.

I'll be very happy looking at a PR for this feature.

Thanks
