### ISSUE TITLE
'as label' in ng-options should be supported by chosen multiple

### ISSUE THREAD

**Issue by AlainD-** [leocaseiro/angular-chosen#214]
Hi,

I'm using a multiple selection with chosen to select some users, but whenever I select one in the list, the selection is not displayed, or disappears after another selection.

I was struggling to figure why the selected items in my list kept disappearing, I just realised that the issue was caused by the fact that chosen does not seem to support the `as label` syntaxt of ngOptions:

```
<select chosen multiple ng-options="user.username as user.fullname for user in vm.uploaders track by user.username" ng-model="vm.users.uploaders"><option></option></select>
```

In my controller, I have
```
vm.uploaders = [
  {username: "user.1", fullname:"User 1", otherAttribute: "some value"},
  {username: "user.2", fullname:"User 2", otherAttribute: "some value"},
  {username: "user.3", fullname:"User 3", otherAttribute: "some value"}
];

vm.users = {
  uploaders: [],
  someCategory: []
}
```

What I expect, is vm.users.uploaders to be populated with just the list of usernames, something like:
```
['user.1', 'user.3']
```

But when I add `user.username as user.fullname` in order to select the username value, it just doesn't work.

**Comment by leocaseiro** [comment]
Hi, have you tried remove the track by $id?

https://plnkr.co/edit/vIOfBUmzCHPosFgAnqHn?p=preview

**Comment by leocaseiro** [comment]
```javascript
var app = angular.module('myApp', ['localytics.directives']);

app.controller('MainCtrl', function($scope, $http) {


  $scope.uploaders = [{
    username: "user.1",
    fullname: "User 1",
    otherAttribute: "some value"
  }, {
    username: "user.2",
    fullname: "User 2",
    otherAttribute: "some value"
  }, {
    username: "user.3",
    fullname: "User 3",
    otherAttribute: "some value"
  }];

  $scope.users = {
    uploaders: ['user.2', 'user.3'],
    someCategory: []
  }

  $scope.items = [];
});
```

```html
<select chosen multiple ng-options="user.username as user.fullname for user in uploaders" ng-model="users.uploaders">
     <option></option>
  </select>
```

**Comment by AlainD-** [comment]
Thank you, that was exactly it! Removing track by fixed my problem. I guess I need to check the documentation of angular again because apparently I did not understand the 'track by' statement correctly.

Thank you again for you help.
