### ISSUE TITLE
Stay open on multi select

### ISSUE THREAD

**Issue by cartifon** [leocaseiro/angular-chosen#215]
Is possible to the angular-chosen menu to stay opened after select an item? Or any chance to be able to close it only by clicking outside the widget area or by pressing ESC??

**Comment by leocaseiro** [comment]
Hi @cartifon, 

Thank you for using angular-chosen.

The chosen is a jQuery library and if you'd like to remain open, you must hold CMD ⌘ or CTRL when selecting options.

Currently there is no option to keep the select option by default on chosen. However, there's an open issue on chosen and you could follow [here](https://github.com/harvesthq/chosen/issues/1546)

**Comment by cartifon** [comment]
Hi @leocaseiro, thanks for the answer.
I tried out and works fine to me.
