### ISSUE TITLE
angular-chosen do not respect  browser_is_supported chosen validation

### ISSUE THREAD

**Issue by adascal** [leocaseiro/angular-chosen#216]
In source code of chosen component where a next lines:

```javascript
    chosen: function(options) {
      if (!AbstractChosen.browser_is_supported()) {
        return this;
      }
      return this.each(function(input_field) {
        var $this, chosen;
        $this = $(this);
        chosen = $this.data('chosen');
        if (options === 'destroy') {
          if (chosen instanceof Chosen) {
            chosen.destroy();
          }
          return;
        }
        if (!(chosen instanceof Chosen)) {
          $this.data('chosen', new Chosen(this, options));
        }
      });
    }
```

As you can see, if browser is not supported, chosen component not applied. 
In that case, we can receive a lot of errors for angular-chosen directive

**Comment by leocaseiro** [comment]
Hi @adascal, thank you for reporting this issue.

I believe it's a [chosen](https://github.com/harvesthq/chosen) issue and it's not related to angular-chosen. 
Would you mind posting this issue in the chosen GitHub?

I'm not sure if I can deal with that.

Thanks

**Comment by adascal** [comment]
Actually it’s a angular-chosen problem.

Cause chosen officially do not support mobile browsers. But your directive try to.
Probably you also need to check if it’s active.
line:

`chosen = element.chosen(options).data('chosen');`

return undefined on mobile browsers cause chosen wasn’t initialized. You need to check that, if you actually have chosen instance. If not, I thing directive should do nothing

**Comment by adascal** [comment]
Actually it’s a angular-chosen problem.

Cause they officially do not support mobile browsers. But your directive try to.
Probably you also need to check if it’s active.

line:

chosen = element.chosen(options).data('chosen');
return undefined on mobile browsers cause chosen wasn’t initialized. You need to that, if you actually have chosen instance. If not, I thing directive should do nothing

**Comment by adascal** [comment]
refs to https://github.com/harvesthq/chosen/pull/1388

**Comment by leocaseiro** [comment]
Thanks @adascal,

I though I'd fix that with e40387ff45b on 1.4.2

What version are you testing it, please?

What browser/device?

**Comment by leocaseiro** [comment]
ping

**Comment by leocaseiro** [comment]
ping @adascal

**Comment by adascal** [comment]
Sorry, was busy a little bit. Yep, looking on commit I can see that it should fix problem. I used old version in production and not checked if problem actual for latest versions. Can close for now.

**Comment by leocaseiro** [comment]
No worries, @adascal!

Thank you for your feedback.

Anything else I could help, please let me know! Thanks!
