### ISSUE TITLE
$event is undefined 

### ISSUE THREAD

**Issue by catch-shailendra** [leocaseiro/angular-chosen#217]
In following code, event passed properly but got undefined.

```
<select chosen  ng-change='fnSelectitem ($event)'>
								<option value="">Select Account</option>
								<option ng-repeat="ac in arrCustUUID track by ac.UUID" value="{{ac.CustAC}}" >{{ac.CustAC}} - {{ac.CustName}}</option>
							</select>

$scope.fnSelectitem = function (e){	
			e.preventDefault() // e is undefined here 
}

```

**Comment by leocaseiro** [comment]
Hi @catch-shailendra, thank you for your issue.

I'm not sure what you're trying to active here. But I couldn't see the `chosen` directive.

Either way, in AngularJS. The easiest way to $watch a select change is with ng-model and [ng-options](https://docs.angularjs.org/api/ng/directive/ngOptions), like so:

```html
<select  
ng-model="account"
ng-change='fnSelectitem ()'
ng-options="item as item.label for item in items track by item.id">
    <option value="">Select Account</option>
</select>
````

```javascript
$scope.items = [{
  id: 1,
  label: 'aLabel',
  subItem: { name: 'aSubItem' }
}, {
  id: 2,
  label: 'bLabel',
  subItem: { name: 'bSubItem' }
}];

$scope.fnSelectitem = function(){ 
    console.log('account', account);
}
```

**Comment by catch-shailendra** [comment]
i forgot to add the directive, let me explain again i have successfully added chosen in my select which is  working fine,& than I want to prevent  select box from being changed if a certain condition applies. Doing this doesn't seem to work:


<select  
ng-model="account"
ng-change='fnSelectitem ($event)' // passing $event properly 
ng-options="item as item.label for item in items track by item.id">
    <option value="">Select Account</option>
</select>


$scope.fnSelectitem = function(e){ 
      if(Some Condition){
         e.preventDefault();
      // Problem is here gtting "e" undefined
        }
}

**Comment by leocaseiro** [comment]
There's no $event on ng-change. 

Try like this:

$scope.items = [{
  id: 1,
  label: 'aLabel',
  subItem: { name: 'aSubItem' }
}, {
  id: 2,
  label: 'bLabel',
  subItem: { name: 'bSubItem' }
}];

$scope.fnSelectitem = function(){ 
    if ( account == 'bSubItem') {
      // do action
    }
}


Perhaps, this plunker might help you https://plnkr.co/edit/lRiqxi?p=preview

**Comment by catch-shailendra** [comment]
@leocaseiro got your point thanks for plunker link.

**Comment by leocaseiro** [comment]
I hope works for you 👍
