### ISSUE TITLE
Select doesn't update when ng-disabled is used withing option tag

### ISSUE THREAD

**Issue by Kharkare** [leocaseiro/angular-chosen#218]
My original question regarding this issue was posted
[here](http://stackoverflow.com/questions/39385093/ng-disabled-doesnt-work-in-angular-chosen?noredirect=1#comment66565242_39385093)

I have used `ng-disabled` withing an `option` tag to enable or disable that option. But the option doesn't seem to update inside angular chosen. Here is the [full example](https://plnkr.co/edit/8ivqmeWGFOOIV2eqkqAa?p=preview). Whenever I select "PDF" as `option` in the first `select box` the "Yes" `option` in the second `select box` should be enabled

**This works IF** I pass an `array` to `ng-options` and update the `objects` property [as shown here](https://plnkr.co/edit/jwLKxH?p=preview), **but doesn't work without `ng-options`**

**Comment by leocaseiro** [comment]
Hi @Kharkare. Thanks for opening the issue here.

I've been trying to fix the use with ng-repeat, however, `angular-chosen` has never worked good without `ng-options`.

Are you able to map your list into an array, perhaps using some kind of iterator?

If you post me more details about your real data, I could help you.

**Comment by Kharkare** [comment]
Hi @leocaseiro. Thanks for your reply

I am neither using `ng-repeat` nor `ng-options`

This is my select tag
```
<select chosen name="maskAccountNumber" id="maskAccountNumber" ng-model="maskAccountNumber" ng-change="checkDisable()" style="width:145px;">
		<option value=""></option>
		<option value="N">No</option>
		<option value="Y" ng-disabled="disableoption">Yes</option>
</select>

The `disableoption` inside `ng-disabled` in last `option tag` is a boolean.
The option doesn't updates(enable/disable) on changing the value of `disableoption`

Please see [here](https://plnkr.co/edit/8ivqmeWGFOOIV2eqkqAa?p=preview)
```

**Comment by leocaseiro** [comment]
Hi @Kharkare,

I'm sorry. I meant that `angular-chosen` doesn't work very well if you don't implement with `ng-options`.

Any chance for you to implement with `ng-options`? Any array would do the job...

With `ng-options` works just as expected:

```javascript

$scope.maskAccountNumber = "N";
$scope.maskOptions = [
   {value: "N", name: "No", disabled: false},
   {value: "Y", name: "Yes", disabled: true}
];
```

```html
<select chosen name="maskAccountNumber" id="maskAccountNumber"
        ng-model="maskAccountNumber"
        ng-options="mask.value as mask.name disable when mask.disabled for mask in maskOptions">
    <option value=""></option>
</select>
```

**Comment by wggley** [comment]
Thanks @leocaseiro I'm 3 hours on this issue and found your answer!
