### ISSUE TITLE
Angular2 and Bootstrap v4

### ISSUE THREAD

**Issue by BenDevelopment** [leocaseiro/angular-chosen#219]
Hi,
Do you plan to update your work to Angular2 and Bootstrap v4 ?
It will be very nice because it's one of the best chosen I've seen so far, great work !

Ben

**Comment by leocaseiro** [comment]
Hi @BenDevelopment,

I've been working with Angular 2 for a while now and I've definitely thought doing that.

I'm a little upset with the chosen team that never accept new features from community, so I might choose `selectize` or `select2` for the directive.

PS: There's a nice select for angular 2 that uses Bootstrap called [ng2-select](http://valor-software.com/ng2-select/)

If you prefer Angular Material style, you can go with [ng2-material-select](https://github.com/Gbuomprisco/ng2-material-select)

**Comment by simison** [comment]
@leocaseiro Here's another one for Select2: https://github.com/angular-ui/ui-select

They _badly_ need a rewrite + maintainers: https://github.com/angular-ui/ui-select/issues/1096

**Comment by shandianjiying** [comment]
Dear,
I will try them, both angular2 and Bootstrap 4 , thank u for your advice

At 2016-09-28 05:15:06, "Benjamin Hoffmann" <notifications@github.com> wrote:


Hi,
Do you plan to update your work to Angular2 and Bootstrap v4 ?
It will be very nice because it's one of the best chosen I've seen so far, great work !

Ben

**Comment by CaosZero** [comment]
Hi do you need some help with Migration to Bootstrap v4 and Angular2?

**Comment by leocaseiro** [comment]
Hi @CaosZero, 
That would be awesome!

I would like to migate to Angular2. However, I don't see any needs for Bootstrap.

**Comment by leocaseiro** [comment]
Hi guys, I've just found a very nice replacement for angular-chosen to be implemented with angular2 and I suggest you guys use that.

It doesn't need jQuery and there are no dependencies, you guys should check it out: https://github.com/basvandenberg/ng-select
