### ISSUE TITLE
Changing max-selected-options does not update angular-chosen

### ISSUE THREAD

**Issue by 321zeno** [leocaseiro/angular-chosen#220]
I am trying to set the limit of selectable elements dynamically but it seems that this config option is not being tracked by angular-chosen.

See [demo plunkr](http://plnkr.co/edit/GEPFvvYCuhYHmLf492Z3?p=preview)

**Comment by leocaseiro** [comment]
Hi @321zeno, thanks for using angular chosen.

The `max-selected-options` specs an attribute value. If you remove the Curly braces, it'll work fine:

```html
<select
        chosen multiple
        max-selected-options="limit"
        ng-model="state"
        ng-options="s.id as s.title for s in states">
  <option value=""></option>
</select>
```

**Comment by leocaseiro** [comment]
Hi @321zeno, thanks for pointing that out.

I'll need to check how to fix that when I get some chance.

I'll might have to call an emit for update the directive, so we can force that.

**Comment by leocaseiro** [comment]
Hi @321zeno, I'm sorry for my delay.

I had a work around this issue which is not the ideal, but works for the time being.
The initOrUpdate() method is called every time the directive loads. With that said, I created a `ng-if`that toggle the directive every time you change the limit. So the chosen is being re-compiled.

```html
<select
        ng-if="show"
        chosen multiple
        max-selected-options="limit"
        ng-model="item.state"
        ng-options="s.id as s.title for s in states">
  <option value=""></option>
</select>
```

```javascript

$scope.show = true;
  
  $scope.increaseLimit = function() {
    $scope.limit++;
    
    $scope.show = false;
    $timeout(function(){
      $scope.show = true;
    });
  }
```

Check my plunker: http://plnkr.co/edit/YvZHeceW87oc2w5ft5Td?p=preview

PS: Make sure you create an object for your ngmodel, like so:

```javascript
$scope.item = {
    state: [3, 2]
};
```

**Comment by 321zeno** [comment]
This solution works for me, thanks for your help (apologies for not replying in time)
