### ISSUE TITLE
Angular-chosen changes selected options when disabled

### ISSUE THREAD

**Issue by Cirivas** [leocaseiro/angular-chosen#223]
As the title says. The code is:

``` html
<select chosen multiple`
    data-placeholder="{{ (!isSesionEditable() || isSesionInitiated()) ? 'Seleccione' : 'Ninguno'}}"
    ng-model="asignacionEjercicio.implementos"
    ng-options="implemento.id as (implemento.nombre + ' - ' + implemento.valor) group by implemento.nombre for implemento in listaImplementos | implementosUsados:asignacionEjercicio.implementosUsadosIds"
    ng-change="onDataChanged()"
    ng-disabled="!isSesionEditable() || isSesionInitiated()"></select>
```

![image](https://cloud.githubusercontent.com/assets/12433683/19690249/6bd159e0-9aa6-11e6-8c8e-cc78b8c85559.png)

When the ng-disabled condition is met, this happens: 

![image](https://cloud.githubusercontent.com/assets/12433683/19690271/8d134528-9aa6-11e6-8a17-94d9cd56dae3.png)

Those are the first options of each group, as you can see in the first image. 

An important thing to note is that this is just a visual thing, since the values stored are those of the first image.

**Comment by leocaseiro** [comment]
Hi @Cirivas, 
First of all thank you for using angular chosen and for reporting this issue.

1. First, please make sure you switch from `data-placeholder` to `placeholder-text-multiple`
2. Make sure you add an empty `<option value=""></option>`


I'm not sure what exactly you are trying to achieve here, but in my tests, the angular-chosen works fine while disabled or enabled: https://plnkr.co/edit/3k1lPQ?p=preview

**Comment by Cirivas** [comment]
Thanks @leocaseiro for your answer.

I made the changes you suggested but nothing changed. I'm trying to achieve the same thing you did in your test, but as I said, the selected options are changed (just in the view). 

Is there anything else I can show to you so you can help me solve this issue?

**Comment by leocaseiro** [comment]
Hi @Cirivas,

I'm not sure what could be wrong.

Are you able to provide me the source of your project?

The only think I'd say is for you to check the versions of Angular, Chosen, jQuery and Angular Chosen. If they match the ones i'm using atm.

Other than that. Copy and paste my example on your application and see if works.

**Comment by Cirivas** [comment]
I can't provide the source code, mostly because it is a huge project. I'm in charge of fixing bugs like these. 

I checked the versions, and maybe here it is the problem. The Angular-Chosen plugin it is from another provider (adityasharat). I thought that it was only one angular-chosne plugin, so I apologize from asking here.

Thanks for your time.

**Comment by leocaseiro** [comment]
Hi @Cirivas, thanks for your reply.

if you switch for this plugin, would work for you?

**Comment by Cirivas** [comment]
I switched the plugin, but now I got problem with CSS: 

![image](https://cloud.githubusercontent.com/assets/12433683/19930124/bc430f78-a0e5-11e6-9a65-b4b2d2f8b884.png)

As I said, the project is kind of big, so to find the source of the error may be very difficult.

Again, thanks for your time.
