### ISSUE TITLE
Changes in model value is not reflected from chosen dropdown text in 1.5.1

### ISSUE THREAD

**Issue by tsampath** [leocaseiro/angular-chosen#227]
### Please mark the options you have done, before open this Issue. We'll prioritize the issues that are consistent and completed.

- [x] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [x] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [ ] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [ ] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

## Please, post your plunker link here:
> (plunker link goes here)

If you need a starter plunker for a single select, use this one: https://plnkr.co/edit/Ec9l1C?p=preview

If you need a starter for a multiple select, use this one: https://plnkr.co/edit/vaRw1x?p=preview

## Write your issue:

I tested my code with chosen code in below plunker. Then it works like charm
http://plnkr.co/edit/SxaKdz?p=preview

**Comment by tsampath** [comment]
Tested on 1.4.1. It works well with that version.

**Comment by leocaseiro** [comment]
Hi @tsampath,

I believe your solution is in the [documentation](http://leocaseiro.github.io/angular-chosen/#multiple-works-better-with-object-child-dot) and is about the `ng-model`:

> As same as any `<select multiple>`, Angular works better with an `object.child`, or .(dot). Watch it: https://egghead.io/lessons/angularjs-the-dot Reference: http://stackoverflow.com/a/17607794/3415716


Here is your plunker with 1.5.1 working with this solution: http://plnkr.co/edit/3Ge10O?p=preview

**Comment by Lobosque** [comment]
I believe he is basically referring to #221 which I am also experiencing.

**Comment by Lobosque** [comment]
For me it starts to break at 1.4.3.
It works well with chosen 1.4.1 and 1.4.2.

**Comment by leocaseiro** [comment]
Hi @Lobosque, thank you for reporting this issue.

The only thing is that I've never really understood #221. So, would you mind opening an issue and giving me details about what's the problem you're having?

Th

**Comment by leocaseiro** [comment]
ping @tsampath ?
