### ISSUE TITLE
data-placeholder and placeholder-text-single documentation bug

### ISSUE THREAD

**Issue by goldbergjeffrey** [leocaseiro/angular-chosen#228]
### Please mark the options you have done, before open this Issue. We'll prioritize the issues that are consistent and completed.

- [X] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [X] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [X] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [X] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

While I see this isssue closed in #181 , the documentation refers to using data-placeholder in the example:
![image](https://cloud.githubusercontent.com/assets/8709292/20844147/86f3513e-b88c-11e6-9452-03b8b8cfc6bc.png)

and the placeholder-text-single reference does not state single quotes need to wrap the string along with double quotes.

Docs show: 
![image](https://cloud.githubusercontent.com/assets/8709292/20844269/feddc2f6-b88c-11e6-966b-1542df3b2bfd.png)

but reading through #181 I found that `placeholder-text-single="'Select a user...'"` is what is required to make it work.

jg

**Comment by leocaseiro** [comment]
Hi @goldbergjeffrey,

Thank you for reporting this issue. I've updated the documentation plunker demo.
It supposed to be exactly what you meant: `placeholder-text-single="'Select a user...'"`

Thanks for that.

**Comment by carmat** [comment]
FYI, the docs [here](http://leocaseiro.github.io/angular-chosen/#chosen-options) still refer to `data-placeholder` instead of `placeholder-text-single`.

**Comment by leocaseiro** [comment]
Hi @carmat, thanks for pointing that out, I'll fix the docs by this weekend, I'll open an issue so I won't forget it. Thanks
