### ISSUE TITLE
to show placeholder in case of multiple 

### ISSUE THREAD

**Issue by firdousalam** [leocaseiro/angular-chosen#230]
### Please mark the options you have done, before open this Issue. We'll prioritize the issues that are consistent and completed.

- [x] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [x] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [x] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [x] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

## Please, post your plunker link here:
> (plunker link goes here)

If you need a starter plunker for a single select, use this one: https://plnkr.co/edit/Ec9l1C?p=preview

If you need a starter for a multiple select, use this one: https://plnkr.co/edit/vaRw1x?p=preview

## Write your issue:

PLEASE ADD THIS INTO YOUR DOCUMENTATION TO SET DEFAULT PLACEHOLDER FOR MULTIPLE CHOOSEN
'
<
select chosen multiple ng-model="location_filter" ng-options="s.cust_location for s in location_name" data-placeholder="LOADING LOCATION" data-placeholder-text-multiple="'SELECT LOCATION'">
	<option value="" disabled> SELECT LOCATION</option>
</select>'

**Comment by firdousalam** [comment]
"'
<select chosen multiple ng-model="location_filter" ng-options="s.cust_location for s in location_name" data-placeholder="LOADING LOCATION" data-placeholder-text-multiple="'SELECT LOCATION'">
								<option value="" disabled> SELECT LOCATION</option>
							</select>
'"

**Comment by leocaseiro** [comment]
Hi @firdousalam, thanks for open this issue, but it's already there http://leocaseiro.github.io/angular-chosen/#chosen-options
