### ISSUE TITLE
Angular Chosen: Two same dropdown list if 1 options select then remove automatically the selected option from other dropdown list

### ISSUE THREAD

**Issue by MuhammadTayyeb** [leocaseiro/angular-chosen#233]
I use chosen multiple select dropdown lists. When selecting the option one from one of the lists then the selected option automatically remove from the drop-down list. the screen short below 

![ozas3](https://cloud.githubusercontent.com/assets/16691821/23177729/b84ea358-f81c-11e6-8fa2-6e271a14f330.png)

**Comment by leocaseiro** [comment]
Hi @MuhammadTayyeb, thanks for openning your issue.

I'm sorry but I didn't understand what your issue at all.

Please, respect the rules of the issues track and mark the options you've done. Also, please share some code. I'm a coder, I read code.

### Please mark the options you have done, before open this Issue. We'll prioritize the issues that are consistent and completed.

- [ ] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [ ] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [ ] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [ ] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

## Please, post your plunker link here:
> (plunker link goes here)


If you need a starter plunker for a single select, use this one: https://plnkr.co/edit/Ec9l1C?p=preview

If you need a starter for a multiple select, use this one: https://plnkr.co/edit/vaRw1x?p=preview

**Comment by MuhammadTayyeb** [comment]
thanks for help.

**Comment by leocaseiro** [comment]
Hi @MuhammadTayyeb, I believe the question from #234 should help you.

**Comment by MuhammadTayyeb** [comment]
thanks for Help

**Comment by leocaseiro** [comment]
I'm glad worked out for you.
