### ISSUE TITLE
List of single element using the same options list 

### ISSUE THREAD

**Issue by bgadiel** [leocaseiro/angular-chosen#234]
Hello,
I am truly sorry if the question was answered in the past, but I wasn't able to find any reference to it  (too many names for the same meaning, i guess):
I have a huge list of single-select elements which all share the same 100 options.
Does angular-chosen support using the same list of options by many select element or should I multiple the options list for each select element and some how keep the synced?

Thanks.

**Comment by leocaseiro** [comment]
Hi @bgadiel. I'm not sure what you'd like to do!

But if you want to share the same directive chosen with the same options list, it's pretty straight forward.

```javascript
    $scope.item1 = {
    selected: 'BRA'
  };

  $scope.item2 = {
    selected: 'USA'
  };

  $scope.item3 = {
    selected: 'CHI'
  };

  //Static items
  $scope.options = [
    {name: "Australia", value: "AUS"},
    {name: "Brazil", value: "BRA"},
    {name: "United States", value: "USA"},
    {name: "England", value: "ENG"},
    {name: "China", value: "CHI"},
    {name: "Japan", value: "JAP"},
  ];
```

```html
      <select chosen
        ng-model="item1.selected"
        ng-options="option.value as option.name for option in options">
        <option value=""></option>
      </select>

      <select chosen
        ng-model="item2.selected"
        ng-options="option.value as option.name for option in options">
        <option value=""></option>
      </select>

      <select chosen
        ng-model="item3.selected"
        ng-options="option.value as option.name for option in options">
        <option value=""></option>
      </select>
```

Demo: https://plnkr.co/edit/Ec9l1C?p=preview

**Comment by bgadiel** [comment]
The problem with this approach is that single-select does not remove the selected item from the options list. (display-selected-options: 'Note: this is for multiple selects only. In single selects, the selected result will always be displayed').
So I guess I need to add/remove the selected value from the options list for each model change event? Is this the right approach for keeping all synced?

**Comment by leocaseiro** [comment]
Oh! I see. Now it's more clear what you expect.

@bgadiel, the `chosen` directive, only apply chosen into an angularjs `<select>`. So, the same way you can use `ng-options` as a function for `<select>`, you can use with `chosen` also.

I suggest you use [lodash.filter](https://lodash.com/docs/4.17.4#filter) or [underscore.filter](http://underscorejs.org/#filter) to filter, but would be something like that:



```html
 <select chosen
        ng-model="item1.selected"
        ng-options="option.value as option.name for option in filterOptions()">
        <option value=""></option>
      </select>

      <select chosen
        ng-model="item2.selected"
        ng-options="option.value as option.name for option in filterOptions()">
        <option value=""></option>
      </select>

      <select chosen
        ng-model="item3.selected"
        ng-options="option.value as option.name for option in filterOptions()">
        <option value=""></option>
      </select>
```

Eq: https://plnkr.co/edit/Ec9l1C?p=preview

**Comment by bgadiel** [comment]
That was very helpful!
Thank you.
