### ISSUE TITLE
Trigger chosen event

### ISSUE THREAD

**Issue by bgadiel** [leocaseiro/angular-chosen#235]
Hi there,
I would like to have a custom max-selected-options functionality, so I am seeking a way of firing chosen:maxselected when reaching a certain limit.
How to trigger a chosen event from the controller please?

Thanks.

**Comment by leocaseiro** [comment]
You can use the `max-selected-options` from chosen as an attribute `max-selected-options` in angular-chosen:

`<select chosen max-selected-options="3">...</select>`

More in the docs http://leocaseiro.github.io/angular-chosen/#chosen-options

**Comment by leocaseiro** [comment]
I've just noticed that you asked how to call a chosen event.

I normally create another directive, so I have more "power", than I can use `element.on()`

Eq:

```html
 <select chosen multiple
    my-custom-trigger
    max-selected-options="2"
    ng-model="item.selected"
    ng-options="option.value as option.name for option in options">
    <option value=""></option>
  </select>

```

```javascript
app.directive('myCustomTrigger', function () {
    return {
      restrict: 'A',
      link: function(scope, element) {
        element.on('chosen:maxselected', function (e, obj) {
          alert('chosen maxselected!');
          console.log(e, obj);
        });
      }
    };
});
```

**Comment by bgadiel** [comment]
This does seems to be the direction I need but my case is a bit complicated than that:
My goal is to trigger max-selected-event when certain conditions met (and not by plain number).
The reason for that is that I have a unique list, which aggregates the selections by a specific parameter and therefore I might have a situation where I have 30 items in 'item.selected' but in 'unique_list' I will have 5.
That's why I need to build custom  event trigger.
so I have a set a watcher on "item.selected" in the controller which listens to every change made:

```
$scope.$watchCollection('item.selected', function (newValues, oldValues) {
                updateUniqueList();
if (unique_list.length > 20) {
// trigger max-selected-event
}
            }
        });
```

How can I bind this watch to the max-selected-event? 
should I move the watch inside the custom directive you suggested and maintain the unique_list inside the directive?

**Comment by leocaseiro** [comment]
I would much simpler than that. I'd create a callback function with `ng-change`. Pretty straight forward, like so:

```javascript

$scope.item = {
    selected: ['BRA'] // needs to be an array
  };

  $scope.options = [
    {name: "Australia", value: "AUS"},
    {name: "Brazil", value: "BRA"},
    {name: "United States", value: "USA"},
    {name: "England", value: "ENG"},
    {name: "China", value: "CHI"},
    {name: "Japan", value: "JAP"},
  ];

 $scope.customMax = function(max) {
    if ($scope.item.selected.length >= max) {
        alert('do wherever I need');
    }
 }
```

```
<select chosen multiple ng-model="item.selected"
      ng-options="option.value as option.name for option in options"
     ng-change="customMax(3)">
    <option value=""></option>
</select>
```

https://plnkr.co/edit/Fi0BEl?p=preview

**Comment by bgadiel** [comment]
how do I trigger max-selected event in customMax?

**Comment by leocaseiro** [comment]
Hi @bgadiel, I'm sorry, the best way would be combining both of them:

```html
<select chosen multiple ng-model="item.selected"
      max-selected-options="3"
      ng-options="option.value as option.name for option in options"
     ng-change="customMax(3)">
    <option value=""></option>
</select>
```

**Comment by bgadiel** [comment]
this is not the behavoiur I need.
I must have failed to explain my needs properly.
lets say you have 2 arrays: regular_arr and filtered_arr. for each 3rd element in regualr_arr, I add one element to filteref_arr. once the filtered_arr reached 3 elements, max-selected trigger would be fired.
so my chosen markup would be:

<select chosen multiple 
ng-model="regular_arr"
      ng-options="option.value as option.name for option in options"
     ng-change="insertElementToFilteredArr()">
    <option value=""></option>
</select>

My question is:
How do I stop the user from adding more elements to regular_arr once I reach max elemenets in filtered_arr?

**Comment by leocaseiro** [comment]
Perhaps you can create a directive with a listener of `chosen:showing_dropdown` and then if is greater than max you call `chosen:close` to close....

It might work. Please, send me a plunker with your code if you need some more help...otherwise it's pretty hard to helps (Sorry)

**Comment by bgadiel** [comment]
of course:
[https://plnkr.co/edit/AnMu38Du86iOuVGOK9Di?p=preview](https://plnkr.co/edit/AnMu38Du86iOuVGOK9Di?p=preview)

**Comment by leocaseiro** [comment]
I think what you want will work better with $scope.$watch;

```javascript
$scope.maxResults = 3;
$scope.$watch('regular_arr', function() {
    $scope.insert_counter = $scope.regular_arr.length;
    
    if ($scope.insert_counter % $scope.maxResults === 0) {
      $scope.filtered_counter = $scope.insert_counter / $scope.maxResults;
    }
});
```

https://plnkr.co/edit/1vAJttDisa1C3MKjW5px?p=preview

**Comment by bgadiel** [comment]
its also might work. But what I really need is your input on what code should be insert instead of:
" alert('max-selected event is triggered here to prevent the user from selecting more values');"
in my plnkr.

**Comment by leocaseiro** [comment]
Have you tried that solution?
https://github.com/leocaseiro/angular-chosen/issues/235#issuecomment-283592784

**Comment by bgadiel** [comment]
yes, but no success. I tried just to open and close but it doesnt work for me.
Any idea what is missing?
[https://plnkr.co/edit/R8amLUvFgZv1a1ePxbIs?p=preview](https://plnkr.co/edit/R8amLUvFgZv1a1ePxbIs?p=preview)

**Comment by leocaseiro** [comment]
It seems the chosen has a bug with the `chosen:close`. You should use the `max-selected-options` to do it.

I created an update function that you can use:

https://plnkr.co/edit/50WaKOCi4WIPxOe2L3f3?p=preview

**Comment by bgadiel** [comment]
Thank you, I replaced the event with 'chosen:maxselected' (although it is not a Triggerable Event). but to be honest, I still don't quite get why my plnkr does not work? What is missing here? (this is exactly the code I need)
[https://plnkr.co/edit/UW5rNutVSlb150qzTrrz?p=preview](https://plnkr.co/edit/UW5rNutVSlb150qzTrrz?p=preview)

**Comment by leocaseiro** [comment]
Try use `max-selected-options` for that.

**Comment by bgadiel** [comment]
yes... but how? Mind showing in my plnkr how to use it?

**Comment by leocaseiro** [comment]
Did you see this one? https://plnkr.co/edit/50WaKOCi4WIPxOe2L3f3?p=preview

**Comment by bgadiel** [comment]
Works!
[https://plnkr.co/edit/UW5rNutVSlb150qzTrrz?p=preview](https://plnkr.co/edit/UW5rNutVSlb150qzTrrz?p=preview)
