### ISSUE TITLE
Could not display search results in Chinese.

### ISSUE THREAD

**Issue by kentkwan** [leocaseiro/angular-chosen#237]
![Image](https://raw.githubusercontent.com/kentkwan/images/master/angular-chosen/chinese.png)
![Image](https://raw.githubusercontent.com/kentkwan/images/master/angular-chosen/number.png)
Could not display search results in Chinese.
It works in English or input numbers.
How can i fix it? Please!

**Comment by leocaseiro** [comment]
Try this https://github.com/doukit/chosen4chinese

**Comment by kentkwan** [comment]
非常感谢

**Comment by kentkwan** [comment]
Thanks a lot.
