### ISSUE TITLE
Can't add empty field in dropdown list.

### ISSUE THREAD

**Issue by gullocean** [leocaseiro/angular-chosen#239]
I just tried to add the empty field in dropdown list.. but it is not showing..

```html
<select ng-model="formData.schOption[schItem.count]"
     chosen 
     ng-options="scheduleGoodsItem.item group by scheduleGoodsItem.group
     for scheduleGoodsItem in scheduleGoodsList track by scheduleGoodsItem.item"
     no-results-text="'Item not found in the list Please add them Manually'">
     <option value=""></option>
</select>
```

Could you please let me know what I missed on above code?

**Comment by leocaseiro** [comment]
Hi @gullocean,

I can't identify any problems with your code. Perhaps if you send me a plunker would be easier to debug.

Use this reference https://plnkr.co/edit/Ec9l1C?p=preview

**Comment by leocaseiro** [comment]
?

**Comment by leocaseiro** [comment]
Closing the issue for lack of response. 

PS: I'm happy to reopen in case @gullocean shows me what the issue is.
