### ISSUE TITLE
ge pass in index 

### ISSUE THREAD

**Issue by jl2l** [leocaseiro/angular-chosen#242]
> If you are going to be lazy asking me properly, I'll be lazy answering to you (@leocaseiro)

### Please make sure you can mark all the options, before open this Issue. I'll prioritise the issues that are consistent and completed. 

- [ ] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [ ] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [ ] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [ ] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

## Please, post your plunker link here:
> (plunker link goes here)

If you need a starter plunker for a single select, use this one: https://plnkr.co/edit/Ec9l1C?p=preview

If you need a starter for a multiple select, use this one: https://plnkr.co/edit/vaRw1x?p=preview

**Comment by leocaseiro** [comment]
????????
