### ISSUE TITLE
Chosen doesn't update when the model changes programmatically

### ISSUE THREAD

**Issue by abyx** [leocaseiro/angular-chosen#244]
> If you are going to be lazy asking me properly, I'll be lazy answering to you (@leocaseiro)

### Please make sure you can mark all the options, before open this Issue. I'll prioritise the issues that are consistent and completed. 

- [x] I've read the documentation on http://leocaseiro.github.io/angular-chosen.
- [x] I've searched on [github issues](https://github.com/leocaseiro/angular-chosen/issues?utf8=%E2%9C%93&q=is%3Aissue) and [stackoverflow](http://stackoverflow.com/questions/tagged/angular-chosen) before open this issue.
- [x] I've tested with the [angular native select input](https://docs.angularjs.org/api/ng/directive/select) without the chosen directive
- [x] I've tested with the oficial [jquery chosen](https://harvesthq.github.io/chosen/) without the angular chosen directive

## Please, post your plunker link here:
> [plunker](http://plnkr.co/edit/giaPbGLcO9R1rc8VH7VU?p=preview)

## Write your issue:

As can be seen in the attached plunker, clicking the button, which updates the model value, does not result in chosen itself getting re-rendered.
This seems to be because of [this line](https://github.com/leocaseiro/angular-chosen/blob/master/src/chosen.coffee#L98) in the code. At least when I'm looking at it, the `.css()` call _always_ returns a value of `0px`, even when the dropdown is closed, which prevents the updated event from getting triggered.

I have no problem creating a PR, but I'm just not sure what that line of code is trying to accomplish. Would it be enough to test whether the dropdown is open (e.g. by checking if the active class is applied)?

**Comment by leocaseiro** [comment]
Hi @abyx, thanks for pointing that out.
I believe it's related to #243 

I would appreciate a PR. 

The fix was made in regards to the scrolling to top #59 and has been done in this commit https://github.com/leocaseiro/angular-chosen/commit/8b7e137f458f26fd643317cfa1102b7ccde5b238

I would need a better solution for fixing that issue. However, I see this issue and the #243 is a priority for most of the users.

**Comment by VanTanev** [comment]
My intuition is that we should remove the overwritten `ngModel.render` and the CSS hack and instead add something like:

```
ngModel.$formatters.push(function(value) {
  initOrUpdate()
  return value
})
```

This is just a guess of the top of my head, haven't had the chance to think through it very deeply.

**Comment by zlodes** [comment]
Same :+1:

**Comment by abyx** [comment]
So, are you guys saying we should just ignore whatever that line was trying to fix? If so I'll send a PR.

**Comment by leocaseiro** [comment]
Hi @abyx, thanks for your keep up.

I would be very happy if the PR fixes the `ngModel` issue as well as keeping the chosen opened while holding the Command(mac)/Ctrl(pc) key.

Thanks

**Comment by abyx** [comment]
Opened pull request #245 will appreciate feedback
