### ISSUE TITLE
chosen directive is not working inside ng-repeat.

### ISSUE THREAD

**Issue by dixant** [leocaseiro/angular-chosen#248]
code is here: I have to use select box inside ng-repeat. because I need select box in multiple rows.
html is here>>
<div ng-repeat="item in items">
      <select
        chosen
        ng-model="item.selected"
        ng-options="option.value as option.name for option in options">
        <option value=""></option>
        </select>
  </div>
...............................................
plunker code is here in attachement>>
[plunk-Ec9l1C.zip](https://github.com/leocaseiro/angular-chosen/files/1323602/plunk-Ec9l1C.zip)

**Comment by leocaseiro** [comment]
Hi @dixant,

I'm sorry I couldn't reproduce your ng-repeat.

The link of your plunker doesn't have any repeats.

http://plnkr.co/edit/Ec9l1C?p=preview

It seems working fine.

**Comment by leocaseiro** [comment]
Closing the issue for lack of response.

PS: I'm happy to reopen in case @dixant shows me what the issue is.
