### ISSUE TITLE
Support for making the optgroup clickable

### ISSUE THREAD

**Issue by Madmancj** [leocaseiro/angular-chosen#250]
When using a select with optgroups, having all the items in a group added to the selection when the group label is clicked would be a very handy feature

For instance, I have a configuration form with all card brands grouped by the issuer. For the moment, if someone wants to select all the card brands issued by a certain issuer, he must select all items one by one. With this feature, he would simply click on the issuer name and all the brands got selected. He can then remove specific brands according to his requirement.

**Comment by leocaseiro** [comment]
Hi @Madmancj, thank you for opening your issue.

The angular chosen is a repo of the jQuery library. 
Unfortunately, there's not such behavior on jQuery Chosen repo. There's an open issue for that. 

https://github.com/harvesthq/chosen/issues/323

**Comment by Madmancj** [comment]
Hi @leocaseiro,

I do agree that the jQuery Chosen has not provided support for making the optgroup clickable.
But having this feature over the top of jQuery Chosen can be extremely useful.

Thanks.

**Comment by VanTanev** [comment]
This is out of scope for this project. Your best approach would be to fork
chosen, add the feature, and use this repo to integrate your fork into
angular.
