### ISSUE TITLE
Reposition search-choice / search-field

### ISSUE THREAD

**Issue by bgadiel** [leocaseiro/angular-chosen#251]
Hi,
This one is more a CSS / HTML related question, and not a bug:
Is it possible to reposition the user selections boxes below / above the search-field (and not inside of it) in Multiple-Select mode?
Currently, each selection (li: 'search-choice') is nested inside ul: 'chosen-choices', but the 'search-field' is also placed as sibling.
Is there a way to change the structure so the selection would be below of the search-field?
Thanks.

**Comment by leocaseiro** [comment]
Hi @bgadiel, I'm not sure.
You can do pretty much everything using CSS to customize it, but you are not able to change the HTML from Chosen as they [hardcoded](https://github.com/harvesthq/chosen/blob/master/coffee/lib/abstract-chosen.coffee#L346) it.

**Comment by bgadiel** [comment]
@leocaseiro, thank you.
