### ISSUE TITLE
1.9.1 Bugfix Release

### ISSUE THREAD

**Issue by VanTanev** [leocaseiro/angular-chosen#256]
**Highlights:**

Close #249

Fix a timing issue for chosen init a157401a1b01f5a73800c0538be3a1b6e0ecdbc2

**Comment by VanTanev** [comment]
@leocaseiro I think this is good enough for a bugfix release, just wanted to check with you before proceeding. If you think it's good I'm gonna do a release tomorrow.

**Comment by leocaseiro** [comment]
Its good to me. I’ve tried many fixes for that. Happy for you to release it.

Many thanks for that.
