### ISSUE TITLE
hide_results_on_select not supported

### ISSUE THREAD

**Issue by cgatesman** [leocaseiro/angular-chosen#257]
hideResultsOnSelect is missing from CHOSEN_OPTION_WHITELIST

**Comment by VanTanev** [comment]
You can use `<select chosen="{ hide_results_on_select: false }">` as a stopgap until we add it.

**Comment by VanTanev** [comment]
Fixed in 08f662a1f62b90e008ec29cbe9398b92cb0edd0c
