### ISSUE TITLE
Creating Select from JavaScript with $compile

### ISSUE THREAD

**Issue by dwilliams999** [leocaseiro/angular-chosen#260]
I am working on creating selectors on the fly based on ajax calls.   I am trying something like this:
    
    var html =
        "<div class=\"form-group mb\">" +
            "<label class=\"col-sm-2 control-label\">" + upperCaseFirst(name) + "</label>" +
                "<div class=\"col-sm-10\">" +
                        "<select chosen=\"" + name + "\" class=\"input-md chosen-select\"" +
                                "ng-model=\"inputs." + name + "\" " +
                                "ng-options=\"__value__ for __value__ in " + name + "\">" +
                            "<option value=\"\">Select a " +  upperCaseFirst(name) + "</option>" +
                    "</select>" +
                "</div></div>"
    angular.element(
        document.getElementById("my-form"))
            .append($compile(html)($scope))

However this fails to create a select control.  It creates a small dropdown which does not render correctly and has no values.  Is this possible using chosen and angular?

**Comment by VanTanev** [comment]
Sorry, this does not pertain to angular-chosen. Try the angular mailing list or #angularjs irc channel.

**Comment by VanTanev** [comment]
But, let me give you a pointer, just because:

It looks to me as if you're writing "jquery-in-angular" instead of writing angular code.

If you supply a complete specification of what you're building, I could give you a better pointer, but it sounds to me like you have an ajax that returns a data structure like:
```json
{
  "inputs": [
    { "name": "my-input", "values": ["one", "two", "three"] }
  ]
}
```
( or at least, something to that effect).

A way to handle this in Angular would be:
```js
// in controller or directive
$scope.models = {}
$http.get('/api/endpoint').then(res => res.data).then(data => {
  $scope.inputs = data.inputs
})
```
```html
// in template
<div ng-repeat="input in inputs">
  <select chosen ng-model="models[input.name]" ng-options="value as value for value in input.values"></select>
</div>
```

**Comment by dwilliams999** [comment]
Hi @VanTanev, thank you for the pointer.  Regarding the code, the definition of the drop down itself is coming from the API, and cannot be written in the template in advance.  I will check with the angular chosen group.  Thanks!

**Comment by VanTanev** [comment]
Hey @dwilliams999, it's fine if the definition comes from the API - the point of angular templates is to be programmable in and of themselves. I have had to implement something similar in the past, it looked like this:

```
  # Options are a hash like::
  # {
  #   "option_name" => {
  #     "value" => "option value",
  #     "type" => "boolean/time/integer..etc",
  #     "label" => "Fancy label",
  #     (opt) "choices" => { "choice_val" => "Choice Label" }, # for type "selection"
  #     "help", "group", "position", "hidden", "allow_per_symbol", # field options, false if not set
  #   },
  #   (opt) "errors" => { "option_name" => ["array", "of", "error", "messages"] },
  # }
```

```html
<div class="form-group" show-errors
     ng-repeat="option_name in option_names"
     ng-class="{'has-error': options.errors[option_name]}"
     ng-if="!options[option_name].hidden"
     >
    <label class="col-md-3 control-label" for="{{ option_name}}">{{ option.label }}:</label>
    <div class="col-md-8">
        <div ng-switch on="option.type">
            <select ng-switch-when="boolean"
                ng-options="opt.value as opt.label for opt in [{label: 'YES', value: true}, {label: 'NO', value: false}]"
                ng-model="option.value"
                id="{{ ::option_name}}"
                class="form-control"
                name="{{ ::option_name}}"
                required=required
            ></select>

            <input ng-switch-when="percent"
                ad-float
                type="text"
                ng-model="option.value"
                id="{{ ::option_name}}"
                class="form-control"
                name="{{ ::option_name }}"
                required=required
            />

            <input ng-switch-when="integer"
                ad-integer
                type="number"
                ng-model="option.value"
                id="{{ ::option_name}}"
                class="form-control"
                name="{{ ::option_name}}"
                required=required
            />

            <ad-time ng-switch-when="time"
                    ng-model="option.value"
                    ></ad-time>

            <select ng-switch-when="selection"
                class="form-control"
                id="{{ ::option_name}}"
                name="{{ ::option_name}}"
                ng-model="option.value"
                ng-options="key as value for (key, value) in option.choices"
                required=required
                ></select>

            <input ng-switch-default
                type="text"
                ng-model="option.value"
                id="{{ ::option_name}}"
                class="form-control"
                name="{{ ::option_name}}"
                required=required
            />
        </div> <!-- ng-switch -->

        <span ng-show="options[option_name].help"
                class="help-block"
                ng-bind="options[option_name].help"
                ></span>

        <span class="help-block"
                ng-show="options.errors[option_name]"
                ng-repeat="error in options.errors[option_name]"
                ng-bind="error"
                ></span>
    </div>
</div>
```

**Comment by dwilliams999** [comment]
Actually @VanTanev, I think I understand the approach you are illustrating.  Let me see if that works and I will get back with you here.

**Comment by dwilliams999** [comment]
Works like a charm, thanks @VanTanev !
