### ISSUE TITLE
How can I Apply title/ tooltip / popover on options of select by using ng-option/ ng-repeat

### ISSUE THREAD

**Issue by Ankushdaharwal** [leocaseiro/angular-chosen#263]
I want to dynamically apply popover on options of select tag **not on select tag but on options** here is my code 

You can further refer to this code in which i need to apply tooltip

    `<select class="form-control" ng-model="selectedCategory2" id="category" style="width:280px;" name="category" ng-change="onselectedchange2(selectedCategory2,DomainLoginId,selectedCategory3)" popover="{{allow}}" popover-trigger="mouseenter" popover-placement="right required>`
`[enter image description here][1]<option ng-repeat=" item in groupData" value="{{item.sso_access_type}}" title="{{allow}}">{{item.sso_access_type}}</option>-->
                            `

   
as per this code The output which I got in Firefox is 

    `<option ng-repeat=" item in groupData" value="S_Adv-Type6" title="Read-Only Access, S Budgets , S Billing" class="ng-binding ng-scope">S_Adv-Type6</option>`

    `<option ng-repeat=" item in groupData" value="S_Adv-Type6" title="Read-Only Access, S Budgets , S Billing" class="ng-binding ng-scope">S_Adv-Type6</option>`

You can see the title for both option become same I want it to be diffrent as in controller.

                            
below is my image link I want like this [[1]: https://i.stack.imgur.com/P32Zl.jpg][1]

  [1]: https://i.stack.imgur.com/P32Zl.jpg

**Comment by VanTanev** [comment]
This is not a bug in angular-chosen.
