### ISSUE TITLE
Load data from remote api while searching

### ISSUE THREAD

**Issue by saadii7** [leocaseiro/angular-chosen#266]
Do not have any plunker link. I used the plugin way before, now need to change the functionality, need to load data while searching too, can you help.

## Write your issue:

Angular chosen select plugin provides a way to search within loaded data. Is there a way to dynamically load data while searching, via any angular event, for example that can be "ng-search"?

**Comment by VanTanev** [comment]
Sorry, but we cannot provide this level of individual support.
