### ISSUE TITLE
When using ng-options on a single select after selecting an option attempting to select the last option will throw this error: "Uncaught TypeError: Cannot set property 'selected' of undefined" 

### ISSUE THREAD

**Issue by findar** [leocaseiro/angular-chosen#27]
It's an off by 1 error.  ng-options is generating the list with n+1 options(the +1 being an empty option).  The solution is to watch the select.length and on change throw an updated call.

Here is the fix, jam it in the linker function:

```
scope.$watch(function(){
    return element[0].length; 
}, function(newvalue, oldvalue){
    if (newvalue !== oldvalue) {
        element.trigger("chosen:updated");
    }
});
```

**Comment by TameshwarNirmalkar** [comment]
thanks that also worked for me.

**Comment by venkateshparihar** [comment]
how to write this inside
ap.directive('chosen3',function(){
	
	var linker = function(scope,element,attr){
		scope.$watch('recipientsLis12',function(){
			
			element.trigger('liszt:updated');
		})
	
		element.chosen();	
	};
	return{
		restrict:'A',
		link: linker,
		
	}
	
})

**Comment by pedro380085** [comment]
findar solution also worked for me.

**Comment by Hasan-git** [comment]
Working 100 %

**Comment by climbican** [comment]
Thank you that worked great for me too!!

**Comment by leocaseiro** [comment]
Hi @climbican, try add an empty '<option></option>'. It should work as well.Hi @climbican, try add an empty '<option></option>'. It should work as well.

**Comment by donotdont** [comment]
https://ashuthinks.wordpress.com/2016/02/18/chosen-js-dropdown-last-select-issue/
