### ISSUE TITLE
Enhanced Search / Custom Search

### ISSUE THREAD

**Issue by ghost** [leocaseiro/angular-chosen#275]
Select Chosen is working great as expected but based on things from end users I would like to define any custom search or if anything implemented already please let me know.

My Option Values 
Gene Eva Convenshun
Amanda Hug
Polly Ester Undawair
Polly Wannakrakouer

When I start search with work  "Polly "
I got 2 results:
**Polly Ester Undawair
Polly Wannakrakouer**

But when continue to "Polly Und"
I would need "**Polly Ester Undawair**" i.e. split words search.

I have tried "search-contains" but no luck, please let me me how ca I do that or any custom method I can implement?

**Comment by VanTanev** [comment]
Check the search options on chosen itself for that, module just integrates Chosen with Angular, without changing any of chosen's functionality: https://harvesthq.github.io/chosen/options.html

**Comment by ghost** [comment]
I have tried options but not working, please let me know what option work for me for that result?

https://jsfiddle.net/54k0rLoz/

**Comment by VanTanev** [comment]
You should ask that in the Chosen repo: https://github.com/harvesthq/chosen

**Comment by ghost** [comment]
Thanks
