### ISSUE TITLE
please add support of "ng-init" directive

### ISSUE THREAD

**Issue by DarkFisk** [leocaseiro/angular-chosen#33]
example:

``` html
<select name="subject" ng-model="contactForm.subject" ng-init="contactForm.subject='value1'" required chosen disable-search="true" width="260">
      <option value="value1">test1</option>
      <option value="value2">test2</option>
      <option value="value3">test3</option>
</select>
```

with 'chosen' directive in hidden (original) select tag present bad option like this (before any changes):

```
<option value="? string:value1 ?"></option>
```

and I got javascript error if I checked last option in chosen select.

P.S. http://jsfiddle.net/darkfisk/UvzZf/
P.S. it seems to me that the initialization of the Chosen happens before the execution ng-init, which causes an error.

**Comment by Armitxes** [comment]
A year old and yet, this is still some issue..

Adding
`terminal: true` or `priority: 451`
both fixes the problem for me, yet I don't want to rewrite the chosen.js source code.

**Comment by mathiasmuller4sh** [comment]
You can fix this bug without changing a word in the chosen file
Add this to your angular config
    app.config(function($provide) {
        $provide.decorator('chosenDirective', function($delegate) {
            var directive = $delegate[0];
            delete directive.terminal;
            directive.priority = 451;
            return $delegate;
        });
    });
