### ISSUE TITLE
allow-single-deselect not compatible with angular filter

### ISSUE THREAD

**Issue by paulpflug** [leocaseiro/angular-chosen#40]
When using allow-single-deselect, the ng-model gets set to null by deselecting which is not compatible with angular filter.

I worked around by manually deleting the property
```coffee-script
for k,v of factory.filter
      if !v
        delete factory.filter[k]
```

**Comment by leocaseiro** [comment]
Hi @paulpflug

**Comment by leocaseiro** [comment]
> Note: the empty `<option value=""></option>` element is mandatory when using `allow-single-deselect`
