### ISSUE TITLE
Google chrome emulate breaks angular-chosen plugin

### ISSUE THREAD

**Issue by okpatil4u** [leocaseiro/angular-chosen#49]
I am using Chosen v1.1.0 with angular-chosen plugin on Google Chrome Version 33.0.1750.149. It works fine until I open browser console to emulate a mobile version and refresh the page. Is there a particular reason for this ?

**Comment by lpsBetty** [comment]
connected to https://github.com/localytics/angular-chosen/issues/67

**Comment by leocaseiro** [comment]
Does the version 1.1.0 release fix your issue? 
We fix the #164 issue, is it similar to your issue?

**Comment by lpsBetty** [comment]
@leocaseiro I found that the chosen divs got not generated at all on mobile, so just normal select inputs!
is this the way it should be? 
![image](https://cloud.githubusercontent.com/assets/244475/13685543/3a2a0be2-e711-11e5-865a-1a24815f50d3.png)

**Comment by leocaseiro** [comment]
I'm not sure what should we do. I believe chosen by itself doesn't work on mobile [chosen#1388](https://github.com/harvesthq/chosen/pull/1388)

For the meantime, perhaps this would solve the issue: http://realize.be/mobile-support-chosen

I'll have a look deep later.

**Comment by leocaseiro** [comment]
Chosen shouldn't be available for Mobile devices. As I posted above, the Chosen library doesn't work on mobile. I'll make sure all mobile devices will show native dropdown instead.

**Comment by leocaseiro** [comment]
Closing this issue with e40387ff45b19fce4ca4a1f5c06d0bee5400348f v1.4.2
