### ISSUE TITLE
data-placeholder expression instead of string

### ISSUE THREAD

**Issue by lanceschi** [leocaseiro/angular-chosen#51]
Hi,

is it possible to pass an expression to ```data-placeholder``` instead of a simple string? It'd be very handy working with i18n applications, and in conjunction with, for instance,  [angular translate](http://angular-translate.github.io/).

Thanks for the great directive!

**Comment by lpsBetty** [comment]
I always use an expression like this:
````
data-placeholder="{{ 'projects.edit' | translate }}"
````

**Comment by ahmed-abdulmoniem** [comment]
Any solution to this issue?

**Comment by lanceschi** [comment]
@develup: I tried both unsuccesfully.
@lpsBetty: is it working for you? I wasn't able to. I'm always getting the default Chosen placeholder text.

I recenlty got back to the project which orginated this issue. I updated the libs to these versions:
- chosen => **1.4.2**
- angular-chosen-localytics => **1.0.7**

I've encountered the same behaviour still, so I decided to modify **angular-chosen-localytics** source in order to have a quick fix. Just edit **chosen.js**:
- New line 50
```javascript
  defaultText = (attr.placeholderExpression !== undefined) ? attr.placeholderExpression : null;
```
- New line 57
```javascript
return defaultText = (defaultText) ? defaultText : chosen.default_text;
```

Here you'll find an example of html markup with the newly placeholder-expression attribute:
```html
<select multiple chosen ng-model="selectModel" ng-options="item.id as item.name for item in selectOptions" placeholder-expression="{{'SELECT_SOMETHING' | translate}}"></select>    
```

Cheers,
Luca

**Comment by lpsBetty** [comment]
@lanceschi yes it is working, I install chosen with bower, don't know what version of chosen is used:
├─┬ angular-chosen-localytics#1.0.7
│ ├── angular#1.3.15 (1.4.0-build.3954+sha.9dfa949 available)
│ └── chosen#e-tag:face03d32

**Comment by lanceschi** [comment]
@lpsBetty: you're right. I made a [codepen](http://codepen.io/lanceschi/pen/bNyymq?editors=101). Translated placeholder works, simple expression doesn't. In my app I'm using the same library versions. The only difference is the size. I don't know for sure, albeit it may be related to the asyncronous nature of translation process ...

**Comment by darlanalves** [comment]
The pull request in #115 enables the use of interpolation in config attributes.

**Comment by lanceschi** [comment]
@darlanalves: big thx! Btw, why does it work in the codepen I posted in this thread?

**Comment by darlanalves** [comment]
@lanceschi I'm not sure. I've tried using exactly the same thing, a interpolation in the data-placeholder attribute, but the chosen plugin gathered the literal value, including the brackets, instead of the interpolated value. 

So I've read the angular-chosen code and seems it keeps the attributes in sync with the chosen plugin options, but the directive evaluates anything on custom attributes, such as `placeholder-text-single`, which is also an issue for me. 

My pull request only checks if the attribute starts with "{{" and uses the interpolated value instead of evaluate it. Maybe it is something in the chosen version used within the directive.

**Comment by ahmed-abdulmoniem** [comment]
I was having the same issue on one of  my views.

I was having two chosen controls (cascading) and it wasn't working ..

When I use resolve (angular ui-router)  the placeholders from the translation started to work and load normally!

**Comment by lpsBetty** [comment]
One time it only worked when my array was available! So I added ``ng-if="array"`` to the ``<select chosen``

Hope this helps!
