### ISSUE TITLE
not working well in tabs (ui.bootstrap.tabs)

### ISSUE THREAD

**Issue by rgodreul** [leocaseiro/angular-chosen#53]
When chosen is used in a tab and that tab is not the 1st tab of the tabset, the widget does not show.

<tabset>
	<tab heading="TabA">
	</tab>
	<tab heading="TabA">
		<select chosen data-placeholder="Pick values" disable-search="true" allow-single-deselect="true" multiple id="skills" ng-model="mymodel" ng-options="myitems" class="chosen-select chosen-ltr"/>
	</tab>
</tabset>

**Comment by leocaseiro** [comment]
Hi, first of all I'd like to apologize for the big delay. This project was abandoned and I'm the new maintainer (Read more #162)

I've got a fix for #179 which probably resolves the same issue with ui-bootstrap tabs and probably any other accordion.

I'm using `$timeout` and this fix will be launched at the next release.

There's a plunker here http://plnkr.co/edit/tVZX6s?p=preview

Make sure you use `width="'100%'"` for better results as responsive as well.

This fix can be used from the branch [/tree/176-ng-if-breaks-inherit-select-classes](https://github.com/leocaseiro/angular-chosen/tree/176-ng-if-breaks-inherit-select-classes)

**Comment by leocaseiro** [comment]
Fixed on release 1.4.0
