### ISSUE TITLE
chosen/select2 abstraction

### ISSUE THREAD

**Issue by iamdey** [leocaseiro/angular-chosen#56]
It would be great to use this library with chosen or [select2](http://ivaynberg.github.io/select2/).

_(I believed select2 was based on chosen but I didn't find any official confirmation)._

I know there's already a [angular-ui ui-select2](https://github.com/angular-ui/ui-select2) but I prefer this one : 

 * $translate 2 support (translations with promises)
 * ngOptions support
 * ...

**Comment by leocaseiro** [comment]
We have ngOptions Support!

For translate, you're able to change 3 messages from Chosen Library.

* ```no-results-text="'No results match'"```
* ```placeholder-text-multiple="'Select Some Options''"```
* ```placeholder-text-single="'Select an Option''"```

Here is an example in Portuguese language: http://plnkr.co/edit/P3bWW2?p=preview
