### ISSUE TITLE
Lexer error when trying to set no-results-text attribute to a string

### ISSUE THREAD

**Issue by SLOBYYYY** [leocaseiro/angular-chosen#57]
When I try to set the html attribute "no-results-text" to a special character (like 'á' or 'é'), angular throws a lexer error since it tries to evaluate it as an expression at line 41:

return options[snakeCase(key)] = scope.$eval(value);

I could solve it by specifically filter this attribute separately but the issue should be addressed IMO

**Comment by leocaseiro** [comment]
Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

Thanks for your report!

We fix that issue with PR #115
