### ISSUE TITLE
How to show default selected for single?

### ISSUE THREAD

**Issue by curlyfro** [leocaseiro/angular-chosen#58]
given the example : Changing the ngModel externally: {{ myPets }}

i removed 'multiple' from the selected and commented out 
    return $scope.myPets.push('hamster'); 
so to only have one selected item.  i expected the select to default to 'cat' but it's still on 'Select an Option'.  is this a bug?  how can i get it to default to 'cat'?

**Comment by sethkrasnianski** [comment]
Also experiencing this as well. Not sure if there's a way to preselect an option based on some criteria or if this is a bug.

Given `ng-options="vendor['public-id'] as vendor.name for vendor in vendors | filter:$viewValue")` and `ngModel="selectedVendor"`. If I preload selectedVendor in the controller with a vendor object that has a name of "Vendor 1", I still see the default select value "Select a vendor".

**Comment by leocaseiro** [comment]
Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

As same you'd do for any `<select>` in Angular, you should set a ngModel as your selected element, like so:

```javascript
$scope.selected = 3;
```

```html
<select
        chosen
        ng-model="selected"
        ng-options="s.id as s.title for s in states">
  <option value=""></option>
```

Example with Multiple(array): http://leocaseiro.github.io/angular-chosen/#selected-quot-selected-quot-from-remote
