### ISSUE TITLE
Don't scroll to top when selecting multiple items with ctrl

### ISSUE THREAD

**Issue by amergin** [leocaseiro/angular-chosen#59]
When selecting multiple items from a dropdown and holding `ctrl`, it would be more user friendly to prevent the default action to scroll to the top of the dropdown menu. I'm dealing with a dropdown of 200+ items and this is an annoying feature, to say at least.

**Comment by leocaseiro** [comment]
Oh I see! I believe that happens while we trigger `chosen:update`, I'll investigate it and I'll try come with a fix to you.

**Comment by mweghorst** [comment]
Any news on this?

**Comment by leocaseiro** [comment]
Hi @mweghorst, I'm really sorry but I tried few times to debug this, but I couldn't find out what was the bug myself.

**Comment by frnan** [comment]
@mweghorst any update on this issue ? ...

**Comment by frnan** [comment]
Fix / Hack proposal :

update <code>initOrUpdate</code> method with 
<code>
initOrUpdate = function() {
            var defaultText;
            if (chosen) {
            	var dropListDom = $(element.parent()).find("div.chosen-drop"); 
            	if (dropListDom && dropListDom.length > 0 && dropListDom.css("left").indexOf("0") >= 0) return; 
              return element.trigger('chosen:updated');
            } else {
              chosen = element.chosen(options).data('chosen');
              if (angular.isObject(chosen)) {
                return defaultText = chosen.default_text;
              }
            }
          };
</code>

**Comment by leocaseiro** [comment]
Hi @frnan, thanks for your suggestion.

I tried to implement that, but it seems working the same way:

https://plnkr.co/edit/g6b4YS?p=preview

**Comment by frnan** [comment]
Thank you for considering my fix / hack proposal.
I m having another scroll issue on the plnkr. It keeps scrolling to the back of the list.
I ll try to take a closer look later on @leocaseiro

**Comment by leocaseiro** [comment]
I've tried to fix that issue many times.

I really appreciate your help. Please let me know if you find any fix.

Cheers

**Comment by frnan** [comment]
Indeed it's a tricky one since it seems related to the <code>trigger("chosen:update");</code> which is from the chosen lib ...

I ll keep you posted @leocaseiro

**Comment by leocaseiro** [comment]
yep...thanks

**Comment by frnan** [comment]
Could you try [here](https://plnkr.co/edit/trh8xUy8GdB3HE8gqTNI?p=preview) @leocaseiro ?
I replaced the angular-chosen-localytics minified js in your previous plnkr with a copy-paste of the version i am using (maybe they are different, I didn't have the time to check yet).

**Comment by leocaseiro** [comment]
Hi @frnan, this is very promisor. Many thanks for this fix. I need to run the tests before release it.

Would you like to send me a PR on the `chosen.coffee` file, so I can test and release this fix?
