### ISSUE TITLE
ng-change on single deselect

### ISSUE THREAD

**Issue by AlJohri** [leocaseiro/angular-chosen#60]
I've been using ng-change on my chosen select box and it's been working quite well; however, the ng-change event doesn't get triggered when using the single deselect feature. Does this need to be implemented on the angular-chosen side?

**Comment by ImranMulani** [comment]
ng-change event doesn't get triggered when using the single deselect ??? how can i do it???

**Comment by leocaseiro** [comment]
Hi, first I'm really sorry for the delay. This project has a new maintainer (Read more #162)

I believe `ng-changed` has been fixed in a later version.

Check my example http://plnkr.co/edit/Zejg6f?p=preview

Even though, you could always use `$scope.$watch` with `ngModel`, like so: 

```javasctipt
$scope.state = ['California', 'Arizona'];
$scope.states = [
    'Alaska',
    'Arizona',
    'Arkansas',
    'California'
  ];
  
  $scope.$watch('state', function(changed) {
    console.log('state changed to ', changed);
  });

```
