### ISSUE TITLE
Cannot set property 'selected' of undefined when selecting last element twice

### ISSUE THREAD

**Issue by sandust** [leocaseiro/angular-chosen#65]
To reproduce
1. Select any option
2. Select the last option
3. "Cannot set property 'selected' of undefined"

Selecting the last option first causes no problem.

Here's a plunkr example: http://plnkr.co/edit/uLls4HEvXSSJOxX1JlUD?p=preview

**Comment by donotdont** [comment]
https://ashuthinks.wordpress.com/2016/02/18/chosen-js-dropdown-last-select-issue/
