### ISSUE TITLE
Dynamic IDs in chosen generated HTML

### ISSUE THREAD

**Issue by Tweety321** [leocaseiro/angular-chosen#70]
Hello,
I have a question regarding dynamic IDs.
I'm generating many <select> boxes and they get their ID by id="{{id}}". e.g. id="test"
When chosen is applied to the select element, the ID of the chosen generated HTML is id="__test___chosen". Is there a way to get the ID to be id="test_chosen" by not setting it hardcoded in the HTML?

I hope you understand my problem and might know an answer.

**Comment by dkavanagh** [comment]
seeing same... investigating.

**Comment by dkavanagh** [comment]
using ng-attr-id did the trick.

**Comment by leocaseiro** [comment]
Hi @Tweety321 and @dkavanagh, first of all, I'm really sorry for delay, however this project has a new maintainer (Read more #162)

I understand both of you are trying to set some ID's, I'm not sure about your scenario, but I believe it's a jQuery(ish) way.

As I know, Chosen by itself or Angular Chosen get's the id from your select and concatenate with "_chosen". With that said, would be enough for you?

```html
<select id="myid" chosen>...</select>
```

Will become:

```html
<select id="myid" chosen>...</select>
<div id="myid_chosen"></div>
```

Again, I'm not sure why you really need ID for your scenario, I would use Angular directives or expressions, like `ng-model` for example. However, with Angular you can create a `ng-repeat` and generate the `{{id}}` as you asked for.

Hope answer your question.

**Comment by dkavanagh** [comment]
Our use case is for automated testing. We have selenium-based tests that often use id or css selectors.
I ended using ng-attr-id="{{ item.name }}" where I had a loop populating several chosen selectors.

**Comment by leocaseiro** [comment]
Awesome! Thank you for your feedback!
