### ISSUE TITLE
must have <option value=""></option> else get error

### ISSUE THREAD

**Issue by lars159** [leocaseiro/angular-chosen#71]
if <option value=""></option>  is left out then on single with deselect localytics goes crazy

test code:
![2014-08-13 15_52_47-mozilla firefox](https://cloud.githubusercontent.com/assets/202926/3906264/6d7e0952-22f1-11e4-8a71-0b59ed5950c5.png)

    simulateAjax([{'name': 'grooo'},{'name': 'gro3oo'},{'name': 'grooo3'},{'name': 'gr1ooo'}, {'name': 'gro1oo'}]).then(function(result) {
        return $scope.optionsFromQuery = result;
      });

  <select
    chosen 
    allow-single-deselect="true"
    data-placeholder="Choose Your Own Adventure"
    no-results-text="'Tough luck'"
    ng-model="foo"
    ng-options="value.name for value in optionsFromQuery"
    style="width:200px;"> 
  </select>

**Comment by leocaseiro** [comment]
Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

Thanks for lettings us know! This is a known issue and it's in the docs.

> Note: the empty `<option value=""></option>` element is mandatory when using `allow-single-deselect`
