### ISSUE TITLE
View not updating when using ng-model without ng-options

### ISSUE THREAD

**Issue by codytaylor** [leocaseiro/angular-chosen#72]
Firstly, thanks for creating this. I use it on some production sites and it generally works great.

I've created a jsfiddle showing the issue in action which is very similar to my code. I hope I'm missing something simple.

http://jsfiddle.net/codytaylor/8oj3qsg1/

Any assistance would be appreciated.

**Comment by jperovic** [comment]
More than year since the last comment... I see the bug is still there...

**Comment by leocaseiro** [comment]
Please try use Angular Chosen 1.3.0+ ang Angular 1.5.0+

It's working for me: http://jsfiddle.net/8oj3qsg1/1/
