### ISSUE TITLE
Setting global variables(translate) in custom script (perhaps angular.config)

### ISSUE THREAD

**Issue by jaakritso** [leocaseiro/angular-chosen#77]
Currently I can add placeholder text, no-results-text and allow-single-deselect only via element attribute.

I couldn't find a way how to add them globally to every element on my custom script. Is it possible at all and if it's not, could you add this kind of option.

**Comment by portus84** [comment]
+++++1

**Comment by leocaseiro** [comment]
Release 1.6.0!

Please read https://github.com/leocaseiro/angular-chosen/pull/231
