### ISSUE TITLE
add support for latest version of chosen

### ISSUE THREAD

**Issue by ispringer** [leocaseiro/angular-chosen#80]
It would be great if you could officially support chosen 1.2.0. There have been a lot of bug fixes since 1.0.0.

**Comment by lpsBetty** [comment]
+1
1.3.0 is already available

**Comment by PhiLhoSoft** [comment]
Now with 1.4.1... Perhaps the dependency in the bower.json file should be removed, letting the project using angular-chosen to make their own dependency, including chosen by themselves.

**Comment by lpsBetty** [comment]
@leocaseiro what do you think about updating the chosen.query to the latest version?
v1.5.1

There are some cool new features and bug fixes: https://github.com/harvesthq/chosen/releases
and I think there will be more events to listen to, maybe it makes some things easier!

Should I take a look or will you?

**Comment by leocaseiro** [comment]
Could you please give a try @lpsBetty?
Let me know if you need any help :smile:
