### ISSUE TITLE
Select cannot be disabled by default

### ISSUE THREAD

**Issue by CarlosCuevas** [leocaseiro/angular-chosen#85]
If the variable ngDisabled is set to is initialized with a truthy value, the select is not disabled. However, if it is initialized to a falsy value, then changed to a truthy value (after some time delay, as changes made too quickly are also not registered), it works as it should.

Example:
```html
<select chosen ng-disabled="selectDisabled"></select>
```

Doesn't work:
```javascript
$scope.selectDisabled=true;
```

This works:
```javascript
$scope.selectDisabled=false;

$timeout(function(){
      $scope.selectDisabled=true;
}, 1000);
```

**Comment by bgutsche** [comment]
I have a similar problem. In my app I have a view and edit mode. Initially if open a view, every field is disabled. Here the angular chosen select is not disabled. If I enable everything and disable everything again. It works fine and is also disabled. I use ng-disabled property.

**Comment by Odi55555** [comment]
I can confirm the issue and debugged a little bit. This happens inside the stopLoading function:
```javascript
stopLoading = function() {
    return element.removeClass('loading').attr('disabled', false).trigger('chosen:updated');
};
```
If you set ng-disabled to true by default, this function enables the select box after loading.
I thought I could just return the value of ng-disabled, but unfortunately I'm not able to access it. I tried:
```javascript
stopLoading = function() {
    return element.removeClass('loading').attr('disabled', element.context.disabled).trigger('chosen:updated');
};
```
But the elements disabled property is true, if ng-disabled is not defined. So this change would disable all fields, if ng-disabled is not defined. The next problem is that the ng-disabled directive seems to be executed after the chosen directive. If there's something like this
```html
  <select
    chosen
   ...
    ng-disabled="false">
    <option value=""></option>
  </select>
```
the value of ```element.context.disabled``` is ```true``` after finishing loading. Later on ```element.context.disabled``` gets ```false```.

So the only solution I can think of is to parse the attributes of the select element and search for ng-disabled. The attribute has a nodeValue which contains a string. This string could be "false" or "disabledScopeVariable". So we would have to check if this is a boolean and if not we would have to get the value with scope.disabledScopeVariable. 

Has someone a better idea? Is it possible to access the ng-disabled value without parsing the elements attributes?

**Comment by mlenser** [comment]
Same issue. Disabled does not apply

**Comment by CarlosCuevas** [comment]
@Odi55555 I've tried your fork and I'm still experiencing the same issue.

**Comment by CarlosCuevas** [comment]
This fork seems to have fixed it: https://github.com/izhangleilei/angular-chosen

**Comment by Odi55555** [comment]
@CarlosCuevas strange, it fixed the issue for us

**Comment by kbhagchandani** [comment]
As pointed by @Odi55555 i have modified the stopLoading function and this has resolved the issue

```javascript 
stopLoading = function() {
    var disable=(attr.ngDisabled)?scope.$eval(attr.ngDisabled):false;
    return element.removeClass('loading').attr('disabled', disable).trigger('chosen:updated');
};
```

However original source code is in coffeescript  and i am not very much familiar  to that please adopt the changes.

**Comment by Odi55555** [comment]
It's been a while since I fixed this, but I think the problem was that the startLoading() function removes  the disabled value if it was initially true. 
```javascript
startLoading = -> element.addClass('loading').attr('disabled', true).trigger('chosen:updated')
stopLoading = -> element.removeClass('loading').attr('disabled', false).trigger('chosen:updated')
```
We have a view with an edit mode, which is initially false. So all fields are disabled after loading the view. But the startLoading() function removes the disabled=true state, that's why I save this state in my fix. In my opinion you have the change both, startLoading() and stopLoading().

I don't see this fix in the solutions from @izhangleilei and @kbhagchandani, but maybe the use case is different. I don't use coffeescript either, but you can compile your fix...

**Comment by azuax** [comment]
For those dealing with this in plain old Javascript, I came up with this approach that solves the situation. Modify from line 42:
```javascript
var initialDisabledStatus;
startLoading = function() {
    initialDisabledStatus = element.attr('disabled');
    if (typeof(initialDisabledStatus) == 'undefined'){
        initialDisabledStatus = false;
    }
    return element.addClass('loading').attr('disabled', true).trigger('chosen:updated');
};
stopLoading = function() {
    return element.removeClass('loading').attr('disabled', initialDisabledStatus).trigger('chosen:updated');
};

**Comment by Sunny-L** [comment]
@azuax  thx
