### ISSUE TITLE
How can i add a new option in angular chosen ?

### ISSUE THREAD

**Issue by abhisheksoni** [leocaseiro/angular-chosen#9]
If i am searching for a text and its not available in the list and i want to add the item in list, it doesnt look like i can add that is there any way i can do that ?

**Comment by pwhty** [comment]
Just finished this in a project. While my requirement was only for multiple selects, it might get anyone looking for this started faster than I did. 
1. Get user input into your database using this tutorial: https://boundlessjourney.wordpress.com/2014/06/12/adding-new-values-to-chosen-plugin/ It plays nice with angular-chosen, no other changes needed. If you only ask for user input once, you're done. 
2. If you need to allow the user to change the selection later, you need to get these new options (that your select element doesn't know anything about) from the model into the option list. The following change was done in chosen.js of angular-chosen-localytics. It iterates all elements of the model array looking for values that are missing in the option list of the select element and adds them to this option list. This is done just before the rendering, which populates the 'selected' field of each option. After that, the original chosen plugin kicks in and transforms the select element to its new look. The code: 
```javascript
if (attr.multiple) {
    $.each(ngModel.$modelValue || [], function (index, value) {
        if (!element.find('option').filter(function () {
            return $(this).html() == value;
        }).length)
        element.append($('<option></option>').text(value));
    });
}
```
Of course, it's not a clean method at all, but it does the trick when you're desperate.
