### ISSUE TITLE
allow-single-deselect="true" dont clean model

### ISSUE THREAD

**Issue by rkmax** [leocaseiro/angular-chosen#92]
If you click on the x the element is deselect but the model still holds the value, i think the correct is nullify the value

**Comment by nicholasmwenda** [comment]
@rkmax did you find a way to solve this? I have the same issue

**Comment by rkmax** [comment]
well i have the select wrapped into a custom directive in the link method i have to force to nullify the value when the .search-choice-cose is removed

```js
el.on('DOMNodeRemoved', '.search-choice-close', function() {
    scope.model = null;
    var listen = scope.$watch('model', function() {
        scope.model = null;
        listen();
    }, true);
});
```

**Comment by leocaseiro** [comment]
Would we need a PR to fix this issue?

**Comment by leocaseiro** [comment]
This probably has been fixed: http://plnkr.co/edit/ueDRv7?p=preview

It's getting null for me while single, and empty while multiple
