### ISSUE TITLE
Selecting a default option

### ISSUE THREAD

**Issue by nextriot** [leocaseiro/angular-chosen#93]
Hi guys:

Thanks for providing the great plugin.

I've been racking my brain for a while now trying to figure out how to implement a default option for the select.

I'm using a data-placeholder attribute with an empty option tag after the select element.
That works fine, however, after a user saves the form, I'm trying to implement the capability to go back a page and have the value show up in the field.

I can get it to show up in the placeholder by doing something like this: data-placeholder="{{ selectedCity || 'City' }}". But I can't overwrite the placeholder (or the default 'Select an option' placeholder) with a default selected option.

I have an ng-model on the select, initiating that with a default value doesn't help.

Any ideas?

Thanks in advance.

**Comment by naumcei** [comment]
It dosen`t work i have tried :(

**Comment by nextriot** [comment]
@naumcei I solved this by doing the following:

ng-model="selectedCity" ng-init="selectedCity = <<DYNAMIC OR STATIC OPTION HERE>>" ng-options="..."

Hopefully that helps you.

**Comment by dkavanagh** [comment]
yes, since ng-model is used to hold the current value, set the current value to the default and chosen will reflect that. I'm doing this in my code. I would say this isn't a bug.

**Comment by sethkrasnianski** [comment]
Does this only work if you set `ng-model` to an option index number? Or can you actually set it a value from the collection being repeated?

**Comment by ivoba** [comment]
@nextriot @dkavanagh can you elaborate on how you got this working?
i cant get this to work, neither with ng-init nor with a prefilled model.
can you give an example for #DYNAMIC OR STATIC OPTION HERE# ?

**Comment by dkavanagh** [comment]
@ivoba, We're still on Angular 1.3. I know some of the ng-options features change in 1.4 and we ran into problems that prevented from updating. That said, our ng-model reflects the value, not an index.

**Comment by leocaseiro** [comment]
Same as #58 

Hi, sorry for the delay, I've just taken this project that was abandoned (read #162).

As same you'd do for any `<select>` in Angular, you should set a ngModel as your selected element, like so:

```javascript
$scope.selected = 3;
```

```html
<select
        chosen
        ng-model="selected"
        ng-options="s.id as s.title for s in states">
  <option value=""></option>
```

Example with Multiple(array): http://leocaseiro.github.io/angular-chosen/#selected-quot-selected-quot-from-remote

**Comment by freemanfx** [comment]
The solution provided in the example doesn't work for grouping. Does anyone have any idea what to do?

**Comment by leocaseiro** [comment]
Hi @freemanfx, I'm afraid is related to issues #243 and #244.

Please install the older version `angular-chosen-localytics@1.4.2` for the time being and see if works.

I apologize as I didn't have time to check what went wrong since [1.4.3](https://github.com/leocaseiro/angular-chosen/tree/1.4.3) yet.

**Comment by freemanfx** [comment]
I already discovered that 1.4.2 should work and it does.
Thank you!
