### ISSUE TITLE
Not working well with ngOptions when data loaded from service

### ISSUE THREAD

**Issue by ankit-saxena** [leocaseiro/angular-chosen#97]
Does not show options when the data is loaded from the service. The same ng-options work for the default select element.

    <select chosen class="form-control"   multiple disable-search="false" 
        allow-single-deselect="true" ng-model="selectedSkills"  data-ng-options="s.ID as s.skillname for s in skills">  
        <option value=""></option>
        </select>
      </div>

**Comment by Linell** [comment]
I'm running into a similar issue. Here is the output generated:
![](https://s3.amazonaws.com/uploads.hipchat.com/83202/834154/vptm5xewVDAGnN6/Screen%20Shot%202015-01-05%20at%201.12.54%20PM.png)

The 'All' item you see is correct -- that's the item that's currently selected. The `result-selected` class on the zeroth item is also correct, that's where `All` is. If I expand the list items, you can even see the dang data. BUT my actual select box looks like this:
![](https://s3.amazonaws.com/uploads.hipchat.com/83202/834154/e6tMNC5KGTXdGsD/Screen%20Shot%202015-01-05%20at%201.09.30%20PM.png)

*(I have three next to each other. Each box is an individual chosen item)*

**Comment by nandhacse** [comment]
Hi @ankit-saxena  @Linell , believe me. i got something that ng-options won't work.
you can use jquery instead. Hope my code will help you.

my html:
    <select chosen id="colleges" ng-model="colleges"></select>

**Comment by leocaseiro** [comment]
Hi, first I'm really sorry for the delay. This project has a new maintainer (Read more #162)

I believe this is an older issue. It seems working fine for me with [ngResource](http://leocaseiro.github.io/angular-chosen/#remote-source-resource) and [$http service](http://leocaseiro.github.io/angular-chosen/#ajax-http) as well.

I'll close this issue, but if you believe is a current bug still, please fork one of my plunks from [example](http://leocaseiro.github.io/angular-chosen/#examples) and show me an example of your scenario.
