### ISSUE TITLE
ng-focus and ng-blur would be a cool feature

### ISSUE THREAD

**Issue by lpsBetty** [leocaseiro/angular-chosen#98]
It would be really cool if ng-focus and ng-blur on a <select chosen> element would work.

**Comment by dudapiotr** [comment]
+1

**Comment by leocaseiro** [comment]
I'd like to, but it's not something that should depend on Chosen by itself?

There's an open Issue there https://github.com/harvesthq/chosen/issues/1428

**Comment by staubesv** [comment]
Hi @leocaseiro, on [harvesthq/chosen#1428](https://github.com/harvesthq/chosen/issues/1428), @ababba15 mentioned a possible solution to the problem on April 3, 2016.

Unfortunately, I'm not a JavaScript developer but I would like to ask whether his suggested way of addressing the problem would be practical to be used for angular-chosen to support ng-focus and ng-blur... What do you think of it?

**Comment by leocaseiro** [comment]
Hi @staubesv, thanks for your link and the update.

I've read his code and it's a little bit hack.

I'm not surprised he didn't send a Pull Request and I wouldn't be surprised if the Chosen team wouldn't accept his changes. They are quite [rigorous](https://github.com/harvesthq/chosen/pull/477) and understand that. A library with so many users needs to be really tested and well maintained.

Either way, it's a solution that might help.
