### ISSUE TITLE
Chosen input not disabled when within a disabled fieldset

### ISSUE THREAD

**Issue by cwmrowe** [leocaseiro/angular-chosen#99]
A chosen input should be disabled when within a fieldset element that is disabled.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attr-disabled

**Comment by bgutsche** [comment]
I have a similar problem. In my app I have a view and edit mode. Initially if open a view, every field is disabled. Here the angular chosen select is not disabled. If I enable everything and disable everything again. It works fine and is also disabled. I use ng-disabled property.

**Comment by portus84** [comment]
+1000!

**Comment by leocaseiro** [comment]
There's an issue on [Chosen/2389](https://github.com/harvesthq/chosen/issues/2389) which means itself don't work well.

Are you able to bind the same disabled with ng-disable of your `<fieldset>`? I know it's not the correct way, but it should solve your problem...

Something like:
```html
<fieldset ng-disabled="editable">
    <select ng-disabled="editable">...</select>
</fieldset>
```

**Comment by leocaseiro** [comment]
Another solution is create a directive to watch the ng-disabled from any fieldset:
```javascript

app.directive('fieldset', function () {
    return {
        restrict: 'E',
        link: function (scope, element, attrs) {

            if (angular.isUndefined(element.prop('disabled'))) { //only watch if the browser doesn't support disabled on fieldsets
                scope.$watch(function () { return element.attr('disabled'); }, function (disabled) {
                    element.find('input, select, textarea').prop('disabled', disabled)
                });
            }
        }
    }
});
```

I found it [here](http://stackoverflow.com/a/24376794/3415716)

**Comment by rvk86** [comment]
Is there any progress on this topic?
